### ISSUE TITLE
Crash in finish_update_squiggles

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#10486]
Hi, I am facing the same issue and I followed the steps you provided by connecting the debugger to the cpptools.exe before opening the file. Please find the exception call stack attached. I would greatly appreciate your assistance in resolving this issue. Thank you very much.

![image](https://user-images.githubusercontent.com/20672821/216233572-42fe30ec-68d5-4323-8f59-16db56864363.png)

```
cpptools.exe!abort() (Unknown Source:0)
cpptools.exe!terminate() (Unknown Source:0)
cpptools.exe!__C_specific_handler_noexcept() (Unknown Source:0)
ntdll.dll!RtlpExecuteHandlerForException() (Unknown Source:0)
ntdll.dll!RtlDispatchException() (Unknown Source:0)
ntdll.dll!KiUserExceptionDispatch() (Unknown Source:0)
KernelBase.dll!RaiseException() (Unknown Source:0)
cpptools.exe!_CxxThrowException() (Unknown Source:0)
cpptools.exe!std::_Xlength_error(char const *) (Unknown Source:0)
cpptools.exe!std::_Xlen_string(void) (Unknown Source:0)
cpptools.exe!std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >::_Construct<1,char const *>(char const * const,unsigned __int64) (Unknown Source:0)
cpptools.exe!gap_buffer::substr(struct msvc::strong_typedef_t<struct msvc::offset_traits>,unsigned __int64) (Unknown Source:0)
cpptools.exe!document::inner::get_line_text(struct msvc::strong_typedef_t<struct msvc::line0_traits>,bool) (Unknown Source:0)
cpptools.exe!document::get_line_text(struct msvc::strong_typedef_t<struct msvc::line0_traits>,bool) (Unknown Source:0)
cpptools.exe!vscode::message_handler::finish_update_squiggles(class vscode::file_uri const &,class std::shared_ptr<class document> const &,class std::shared_ptr<class intellisense_client> const &,class std::vector<struct cpp_intellisense::ISenseErrorEntry,class std::allocator<struct cpp_intellisense::ISenseErrorEntry> > &) (Unknown Source:0)
cpptools.exe!vscode::message_handler::cpptools_finishUpdateSquiggles(void) (Unknown Source:0)
cpptools.exe!vscode::message_handler::dispatch(class vscode::vscode_client_message &&,struct vscode::message_handler::msg_proc_thread_token) (Unknown Source:0)
cpptools.exe!`vscode::message_handler::main_loop'::`2'::<lambda_1>::operator()() (Unknown Source:0)
cpptools.exe!msvc::thread_helper_t::thread_entry(void *) (Unknown Source:0)
cpptools.exe!thread_start<unsigned int (__cdecl*)(void *),1>() (Unknown Source:0)
kernel32.dll!BaseThreadInitThunk() (Unknown Source:0)
ntdll.dll!RtlUserThreadStart() (Unknown Source:0)
```

_Originally posted by @skyran1278 in https://github.com/microsoft/vscode-cpptools/issues/10269#issuecomment-1413184273_

**Comment by sean-mcmanus** [comment]
@skyran1278 Does this crash repro with 1.13.9, 1.14.1, or both? Do you have any other repro details?

**Comment by sean-mcmanus** [comment]
@skyran1278 Do you know of a repro file? It looks like we're trying to get an invalid line of text associated with an IntelliSense error.

**Comment by sean-mcmanus** [comment]
@skyran1278 Also, what is the file encoding?

**Comment by sean-mcmanus** [comment]
@skyran1278 Also, you should try 1.14.1 (pre-release) since it has some crash fixes.

**Comment by skyran1278** [comment]
To answer your questions, the crash reproduces with both version 1.13.9 and 1.14.2. The codebase uses a combination of UTF-8-BOM and BIG5 encoding.

Unfortunately, I do not have a repro file that I can share as it is part of our company's confidential codebase. However, I have attached the report message from version 1.14.2 for your reference.

We have tried the latest pre-release version 1.14.2 and unfortunately, it did not resolve the issue. However, we did observe that the issue does not occur in version 1.12.4.

If there is any additional information I can provide to help resolve the issue, please let me know.

Thank you again for your help.

![image](https://user-images.githubusercontent.com/20672821/218010063-44317703-27b4-4916-8f04-9701a1fc7519.png)

**Comment by sean-mcmanus** [comment]
Yeah, are you able to isolate what type of text is causing the crash to create a minimal repro without revealing any confidential source code, such as by removing code from the file until it stops crashing? i.e. does repro with certain characters? does it repro with a file that doesn't generate any error squiggles? Are you errors being returned in English? (We fixed a crash in 1.14.0 regarding the French language pack).

**Comment by skyran1278** [comment]
I am having difficulty pinpointing the exact action or file that is causing the crash. The crash seems to occur when browsing through many files. Currently, I am in the process of creating a minimal reproduction to isolate the issue. However, in the meantime, I can provide you with more information that may be useful, such as the debug console and call stack when the crash occurs.
```
DEBUG CONSOLE
<- (E) {"seq":1565390,"type":"event","event":"output","body":{"category":"console","output":"Exception thrown at 0x00007FFE999E051C in cpptools.exe: Microsoft C++ exception: std::length_error at memory location 0x000000B4B54FD990.\n"}}
Exception thrown at 0x00007FFE999E051C in cpptools.exe: Microsoft C++ exception: std::length_error at memory location 0x000000B4B54FD990.
<- (E) {"seq":1565392,"type":"event","event":"stopped","body":{"reason":"exception","threadId":13840,"text":"Unhandled exception at 0x00007FF7070F2F21 in cpptools.exe: Fatal program exit requested.","allThreadsStopped":true}}
-> (C) {"command":"threads","type":"request","seq":255}
<- (R) {"seq":1565395,"type":"response","request_seq":255,"success":true,"command":"threads","body":{"threads":[{"id":14564,"name":"Main Thread"},{"id":23524,"name":"ntdll.dll!TppWorkerThread\u001E()"},{"id":12952,"name":"ntdll.dll!TppWorkerThread\u001E()"},{"id":6096,"name":"ntdll.dll!TppWorkerThread\u001E()"},{"id":5992,"name":"ntdll.dll!TppWorkerThread\u001E()"},{"id":23884,"name":"ntdll.dll!TppWorkerThread\u001E()"},{"id":12844,"name":"cpptools.exe!thread_start<unsigned int (__cdecl*)(void *),1>"},{"id":12860,"name":"Worker Thread: 0"},{"id":3936,"name":"ntdll.dll!TppWorkerThread\u001E()"},{"id":9344,"name":"Worker Thread: 1"},{"id":20968,"name":"Worker Thread: 2"},{"id":12600,"name":"Worker Thread: 3"},{"id":23360,"name":"Worker Thread: 4"},{"id":9832,"name":"Worker Thread: 5"},{"id":22588,"name":"Worker Thread: 6"},{"id":1844,"name":"Worker Thread: 7"},{"id":7112,"name":"Worker Thread: 8"},{"id":23304,"name":"Worker Thread: 9"},{"id":22052,"name":"Worker Thread: 10"},{"id":19204,"name":"Worker Thread: 11"},{"id":8300,"name":"Threadpool Scheduler"},{"id":20936,"name":"cpptools.exe!thread_start<unsigned int (__cdecl*)(void *),1>"},{"id":13840,"name":"message processing"},{"id":25652,"name":"cpptools.exe!thread_start<unsigned int (__cdecl*)(void *),1>"},{"id":1576,"name":"Folding ranges thread"},{"id":7768,"name":"parse_root thread"},{"id":6940,"name":"populate_filename_cache thread"},{"id":20144,"name":"cpptools.exe!thread_start<unsigned int (__cdecl*)(void *),1>"},{"id":12908,"name":"document symbol thread"},{"id":22992,"name":"parse file thread"},{"id":23992,"name":"cpptools.exe!thread_start<unsigned int (__cdecl*)(void *),1>"},{"id":3428,"name":"Interval Timer"},{"id":12448,"name":"cpptools.exe!thread_start<unsigned int (__cdecl*)(void *),1>"},{"id":12196,"name":"create decl def scan thread"},{"id":29632,"name":"cpptools.exe!thread_start<unsigned int (__cdecl*)(void *),1>"},{"id":23976,"name":"cpptools.exe!thread_start<unsigned int (__cdecl*)(void *),1>"},{"id":25368,"name":"cpptools.exe!thread_start<unsigned int (__cdecl*)(void *),1>"},{"id":17060,"name":"cpptools.exe!thread_start<unsigned int (__cdecl*)(void *),1>"},{"id":24408,"name":"cpptools.exe!thread_start<unsigned int (__cdecl*)(void *),1>"}]}}
-> (C) {"command":"stackTrace","arguments":{"threadId":13840,"startFrame":0,"levels":20},"type":"request","seq":256}
<- (R) {"seq":1565398,"type":"response","request_seq":256,"success":true,"command":"stackTrace","body":{"stackFrames":[{"id":1000,"name":"cpptools.exe!abort\u001E()","line":0,"column":0,"instructionPointerReference":"0x00007FF7070F2F21","moduleId":1000},{"id":1001,"name":"cpptools.exe!terminate\u001E()","line":0,"column":0,"instructionPointerReference":"0x00007FF7070A160D","moduleId":1000},{"id":1002,"name":"cpptools.exe!__C_specific_handler_noexcept\u001E()","line":0,"column":0,"instructionPointerReference":"0x00007FF70711BB9E","moduleId":1000},{"id":1003,"name":"ntdll.dll!RtlpExecuteHandlerForException\u001E()","line":0,"column":0,"instructionPointerReference":"0x00007FFE9C193EAF","moduleId":1001},{"id":1004,"name":"ntdll.dll!RtlDispatchException()","line":0,"column":0,"instructionPointerReference":"0x00007FFE9C10EAE6","moduleId":1001},{"id":1005,"name":"ntdll.dll!KiUserExceptionDispatch\u001E()","line":0,"column":0,"instructionPointerReference":"0x00007FFE9C192E9E","moduleId":1001},{"id":1006,"name":"KernelBase.dll!RaiseException\u001E()","line":0,"column":0,"instructionPointerReference":"0x00007FFE999E051C","moduleId":1003},{"id":1007,"name":"cpptools.exe!_CxxThrowException\u001E()","line":0,"column":0,"instructionPointerReference":"0x00007FF707093298","moduleId":1000},{"id":1008,"name":"cpptools.exe!std::_Xlength_error(char const *)","line":0,"column":0,"instructionPointerReference":"0x00007FF70705FAA2","moduleId":1000},{"id":1009,"name":"cpptools.exe!std::_Xlen_string(void)","line":0,"column":0,"instructionPointerReference":"0x00007FF70616A5C0","moduleId":1000},{"id":1010,"name":"cpptools.exe!std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >::_Construct<1,char const *>(char const * const,unsigned __int64)","line":0,"column":0,"instructionPointerReference":"0x00007FF706177C77","moduleId":1000},{"id":1011,"name":"cpptools.exe!gap_buffer::substr(struct msvc::strong_typedef_t<struct msvc::offset_traits>,unsigned __int64)","line":0,"column":0,"instructionPointerReference":"0x00007FF7064821D5","moduleId":1000},{"id":1012,"name":"cpptools.exe!document::inner::get_line_text(struct msvc::strong_typedef_t<struct msvc::line0_traits>,bool)","line":0,"column":0,"instructionPointerReference":"0x00007FF70648346B","moduleId":1000},{"id":1013,"name":"cpptools.exe!document::get_line_text(struct msvc::strong_typedef_t<struct msvc::line0_traits>,bool)","line":0,"column":0,"instructionPointerReference":"0x00007FF706485415","moduleId":1000},{"id":1014,"name":"cpptools.exe!vscode::message_handler::finish_update_squiggles(class vscode::file_uri const &,class std::shared_ptr<class document> const &,class std::shared_ptr<class intellisense_client> const &,class std::vector<struct cpp_intellisense::ISenseErrorEntry,class std::allocator<struct cpp_intellisense::ISenseErrorEntry> > &)","line":0,"column":0,"instructionPointerReference":"0x00007FF706293E8C","moduleId":1000},{"id":1015,"name":"cpptools.exe!vscode::message_handler::cpptools_finishUpdateSquiggles(void)","line":0,"column":0,"instructionPointerReference":"0x00007FF706292A52","moduleId":1000},{"id":1016,"name":"cpptools.exe!vscode::message_handler::dispatch(class vscode::vscode_client_message &&,struct vscode::message_handler::msg_proc_thread_token)","line":0,"column":0,"instructionPointerReference":"0x00007FF706268883","moduleId":1000},{"id":1017,"name":"cpptools.exe!`vscode::message_handler::main_loop'::`2'::<lambda_1>::operator()()","line":0,"column":0,"instructionPointerReference":"0x00007FF70626119A","moduleId":1000},{"id":1018,"name":"cpptools.exe!msvc::thread_helper_t::thread_entry(void *)","line":0,"column":0,"instructionPointerReference":"0x00007FF706FE2C5F","moduleId":1000},{"id":1019,"name":"cpptools.exe!thread_start<unsigned int (__cdecl*)(void *),1>()","line":0,"column":0,"instructionPointerReference":"0x00007FF7070CE6BA","moduleId":1000}],"totalFrames":22}}
```

```
CALL STACK
cpptools.exe!abort() (Unknown Source:0)
cpptools.exe!terminate() (Unknown Source:0)
cpptools.exe!__C_specific_handler_noexcept() (Unknown Source:0)
ntdll.dll!RtlpExecuteHandlerForException() (Unknown Source:0)
ntdll.dll!RtlDispatchException() (Unknown Source:0)
ntdll.dll!KiUserExceptionDispatch() (Unknown Source:0)
KernelBase.dll!RaiseException() (Unknown Source:0)
cpptools.exe!_CxxThrowException() (Unknown Source:0)
cpptools.exe!std::_Xlength_error(char const *) (Unknown Source:0)
cpptools.exe!std::_Xlen_string(void) (Unknown Source:0)
cpptools.exe!std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >::_Construct<1,char const *>(char const * const,unsigned __int64) (Unknown Source:0)
cpptools.exe!gap_buffer::substr(struct msvc::strong_typedef_t<struct msvc::offset_traits>,unsigned __int64) (Unknown Source:0)
cpptools.exe!document::inner::get_line_text(struct msvc::strong_typedef_t<struct msvc::line0_traits>,bool) (Unknown Source:0)
cpptools.exe!document::get_line_text(struct msvc::strong_typedef_t<struct msvc::line0_traits>,bool) (Unknown Source:0)
cpptools.exe!vscode::message_handler::finish_update_squiggles(class vscode::file_uri const &,class std::shared_ptr<class document> const &,class std::shared_ptr<class intellisense_client> const &,class std::vector<struct cpp_intellisense::ISenseErrorEntry,class std::allocator<struct cpp_intellisense::ISenseErrorEntry> > &) (Unknown Source:0)
cpptools.exe!vscode::message_handler::cpptools_finishUpdateSquiggles(void) (Unknown Source:0)
cpptools.exe!vscode::message_handler::dispatch(class vscode::vscode_client_message &&,struct vscode::message_handler::msg_proc_thread_token) (Unknown Source:0)
cpptools.exe!`vscode::message_handler::main_loop'::`2'::<lambda_1>::operator()() (Unknown Source:0)
cpptools.exe!msvc::thread_helper_t::thread_entry(void *) (Unknown Source:0)
cpptools.exe!thread_start<unsigned int (__cdecl*)(void *),1>() (Unknown Source:0)
```

**Comment by skyran1278** [comment]
Thank you for your suggestion. I have attempted to use version 1.14.3, however, the crash still persists. I will continue my investigation and attempt to create a minimal reproduction in order to isolate the issue.

**Comment by sean-mcmanus** [comment]
FYI, a user reported a repro at https://github.com/microsoft/vscode-cpptools/issues/10486

**Comment by sean-mcmanus** [comment]
We're tracking this with https://github.com/microsoft/vscode-cpptools/issues/10598 . We plan to have a fix in tomorrow's 1.14.4.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.14.4
