### ISSUE TITLE
clang-format/tidy version comparisons fail for some builds

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#12806]
### Bug Summary 

When the user has installed their own version of clang-format or clang-tidy, but has not specified a specific path to the binary, we will compare one from the user's environment with the one we bundle in the extension to see which version is newer.

The logic currently expects the third token in the version query output to be the version number, but this is not always the case.  I think a more robust solution might attempt to convert each token to a semver until we find a valid one in case there are more or less tokens in the output.

RE: #12718

**Comment by bshoshany** [comment]
Thanks for working on this bug! Perhaps simply doing a match for `/\d+\.\d+\.\d+/` or a similar regex in the output of `clang-tidy --version` would be easier?

Also, please consider [my comment in #12718](https://github.com/microsoft/vscode-cpptools/issues/12718#issuecomment-2394878938).

**Comment by bobbrow** [comment]
It seems the code was being very strict in the token parsing and doesn't like that LLVM is in your string instead of the name of the binary `clang-format` or `clang-tidy`. I have a PR that loosens the restrictions and should deal with additional tokens.

**Comment by sean-mcmanus** [comment]
@bshoshany A fix is available in https://github.com/microsoft/vscode-cpptools/releases/tag/v.1.22.8 .

**Comment by bshoshany** [comment]
@sean-mcmanus thanks! I tried it and it does use `clang-tidy` from the environment instead of the bundled one without specifying the path explicitly. However, the related issue I mentioned, #12804, is not fixed. Even though the correct version is now used, the URL to the docs still has v18.1.6 hard-coded into it. You can see it here:

https://github.com/microsoft/vscode-cpptools/blob/292d84f55af235b7902daae4d29a6ae0ca4a8d50/Extension/src/LanguageServer/codeAnalysis.ts#L381

So maybe the version that is determined in `settings.ts` should be cached and then inserted into this URL?
