### ISSUE TITLE
The language server crashed

### ISSUE THREAD

**Issue by ibousio** [microsoft/vscode-cpptools#1975]
Notification reports "The language server crashed 5 times in the last 3 minutes. It will not be restarted."
I've tried reboot/restart etch.

System Info:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian

**Vscode version** 
Version 1.23.0
Commit 7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45
Date 2018-05-03T15:23:19.356Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64 

**C/C++ for Visual Studio Code:**
Version 0.17.0: May 7, 2018

**C++ Intellisense**
0.2.2

**OUTPUT**
[Error - 12:03:26 PM] Connection to server got closed. Server will not be restarted.

**Comment by bobbrow** [comment]
Are you able to share any details about the project you are working on so we can try to reproduce this issue?  We'll need a little more information to make this actionable, as the projects we've tested on Linux are working for us.

**Comment by ibousio** [comment]
Sorry but is not permitted to send any code info. Is there any log available about language server that I can send you?

**Comment by AnClark** [comment]
I also got the same problem. Even I have restarted VS Code or reloaded this extension for several times, the problem still remains.

**Info of my environment**
- VS Code: 1.23.1
- C/C++ Extension: 0.17.0

**Log in Chromium Developer Tools**
```
[Extension Host] Telemetry enabled!
console.ts:136 [Extension Host] activating extension
console.ts:136 [Extension Host] starting language server
notificationsAlerts.ts:39 The language server crashed 5 times in the last 3 minutes. It will not be restarted.
e.onDidNotificationChange @ notificationsAlerts.ts:39
(anonymous) @ notificationsAlerts.ts:28
e.fire @ event.ts:140
e.notify @ notifications.ts:127
e.notify @ notificationService.ts:65
e._showMessage @ mainThreadMessageService.ts:86
e._showMessage @ mainThreadMessageService.ts:47
e.$showMessage @ mainThreadMessageService.ts:41
e._doInvokeHandler @ rpcProtocol.ts:265
e._invokeHandler @ rpcProtocol.ts:250
e._receiveRequest @ rpcProtocol.ts:196
e._receiveOneMessage @ rpcProtocol.ts:178
(anonymous) @ rpcProtocol.ts:111
(anonymous) @ rpcProtocol.ts:307
e.fire @ event.ts:140
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
```

**Comment by ibousio** [comment]
AnClark  what is your Java setup?

**Comment by AnClark** [comment]
Er... VS Code is based on JavaScript instead of Java.

**Comment by bobbrow** [comment]
[Instructions for enabling logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md)

If that doesn't work because VS Code unloads our extension and clears the log, there is an alternate way to write files to disk instead, but let's see if this works first.

**Comment by bobbrow** [comment]
addendum: you might want to try setting the logging level to the string `"6"` instead of `"Information"` like the instructions say as you will get a bit more information.

Another thing to check (a bug we just fixed) is if your `includePath` contains any direct paths to files (for example: `${workspaceFolder}/include/header.h`)  There should only be folder paths in this setting and we've seen a few users in our telemetry get a ton of crashes when they are configured incorrectly.

**Comment by arcanis** [comment]
> If that doesn't work because VS Code unloads our extension and clears the log, there is an alternate way to write files to disk instead, but let's see if this works first.

What's the procedure? I have a similar issue but cannot see the errors, they're going away too fast

**Comment by bobbrow** [comment]
The log-to-file method is [documented here](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Archive/Enabling%20logging.md).  Though you may want to set the logging level to 6 instead of 5 as the document states.

VS Code has been unpredictable with me in the past about environment variables (at least on Windows), so it's best to launch code from a terminal window/command prompt where you can verify the environment is set before launching VS Code.

**Comment by arcanis** [comment]
Just tried, I just get zero-bytes files, even with the loglevel 6 😞

**Comment by bobbrow** [comment]
In the released version of the extension, we don't call flush on the logging (to avoid unnecessary slowdowns).  It should flush when the extension unloads.  Can you try reloading the window and see if stuff gets written to the file?

**Comment by arcanis** [comment]
Nope, none of the files contain anything, even after I reload or close the window or vscode. I do get a lot of logs in the Output tabs when the editor isn't crashing (cf my other issue), but even then the generated on-disk logfile is empty.

**Comment by bobbrow** [comment]
Did you launch code from a CMD prompt with the variable set?  This works for me with 0.17.0 (I just tried), but I've had these variables set globally for months and have gone through many reboot cycles on Windows.

**Comment by arcanis** [comment]
Yep, from the CMD prompt. Not sure why it happened ... fortunately, solving the other issue also got rid of the crash cycle on the affected file, so it's all good for me. Maybe someone else will be able to generate better logs!

**Comment by bobbrow** [comment]
I don't know what VS Code is doing, but for some reason they don't always seem to respect the environment.  I've made it work in the past by setting global environment variables and then rebooting.

**Comment by bobbrow** [comment]
But you did say that the log file was being created earlier, just with no contents, right?  There's something weird about that because as soon as we create the file we write the logging level to it (because of the env variable issue I mentioned previously).  Unless we were unable to get write permissions to the file, I can't think of a reason why we would be able to create the file but not write that first line to it.

**Comment by arcanis** [comment]
Yep I configured `D:\` as log target, since I know I have full access to it, so it should have worked 😐 And since the files were created, it's likely the environment has been correctly picked up ...

**Comment by bobbrow** [comment]
Oh well.  I guess you can remove the env variables now so we don't spew empty files all over your D: drive 😉

**Comment by OmarKSH** [comment]
I have the same issue and i tried to gather logs but i got the same problems that arcanis ran into (all the log files are empty) i had the latest version of vscode-cpptools (0.17.0) but i downloaded the vsix file of 0.17.0 from the releases page anyway and tried reinstalling, somehow that got everything working again no idea why. I hope this helps others who are having the same problem

**Comment by UR3IQO** [comment]
I had the same problem after upgrading to cpptools 0.17.1 ( VSCode 1.23.1 x64 on Windows 8 x64), so I rolled back to 0.16.1, then upgraded to 0.17.0 and now it works. It looks like something is broken in the 0.17.1.

**Comment by sean-mcmanus** [comment]
@sov1178 Yeah, sorry about that. 0.17.1 has known crashes, particularly when recursive includes paths are used (or no c_cpp_properties.json). We'll try to release a more stable version soon (https://github.com/Microsoft/vscode-cpptools/issues/2006 ).

**Comment by sean-mcmanus** [comment]
@sov1178 We have an insider build you can try that may have the fix: https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.17.2-insiders . The official release is planned tomorrow unless we get delayed by finding more bugs.

**Comment by UR3IQO** [comment]
@sean-mcmanus I have tried the 0.17.2-insiders with no luck - it crashes as the 0.17.1 one. Rolled back to 0.17.0.

**Comment by sean-mcmanus** [comment]
@sov1178 Yikes, must be a different crash. Does the crash occur immediately on startup? The released 0.17.2 will have symbols available on Windows, so users can attach a debugger to get a call stack of the crash without sending a dmp. I don't think we'll be able to fix this crash without a repro or call stack.

**Comment by UR3IQO** [comment]
@sean-mcmanus 
> Does the crash occur immediately on startup?

Yes, it crashes on startup

> The released 0.17.2 will have symbols available on Windows, so users can attach a debugger to get a call stack of the crash without sending a dmp

I will have some time on weekend. Would you provide some instructions to help you catch the problem?

**Comment by sean-mcmanus** [comment]
@sov1178 If it crashes on startup, you'll need to get the debugger to attach before the crash occurs. The best way is probably to clone our repository (preferably the "release" branch), put a break on line 245 of client.ts (util.setProgress(util.getProgressExecutableStarted());), use Launch Extension, after the breakpoint hits, use another VS Code instance to do a (Windows) Attach to `.vscode/extensions/ms-vscode.cpptools-0.17.3/bin/Microsoft.VSCode.CPP.Extension.exe` (not the one ending with IntelliSense.Msvc.exe), with a launch.json with a configuration similar to:

```
...
        {
            "name": "(Windows) Attach",
            "type": "cppvsdbg",
            "request": "attach",
            "processId": "${command:pickProcess}",
            "symbolSearchPath": "http://msdl.microsoft.com/download/symbols",
            "logging": {
                "engineLogging": true
            }
        }
...
```
(i.e. from the Add Configuration... button and the C/C++: (Windows) Attach snippet).
The Call Stack should show crash info for the thread that crashes.
![image](https://user-images.githubusercontent.com/19859882/40505587-843fe352-5f49-11e8-8e05-4a098ef97223.png)

**Comment by chongchai** [comment]
@sean-mcmanus I also got the same problem with the error `Connection to server got closed. Server will not be restarted.` 
My extension is C/C++ 0.17.3 and os is windows 7.

**Comment by sean-mcmanus** [comment]
@chongchai You should upgrade to 0.17.4 which fixed some crashes, or 0.17.5-insiders, which fixed more crashes (assuming we didn't introduce any new ones): https://github.com/Microsoft/vscode-cpptools/releases . If you continue to get crashes, please attach a debugger to Microsoft.VSCode.CPP.Extension.exe and/or create a dmp and provide the call stack of the crashing thread. Windows binaries have symbols available in VS Code by setting your "symbolSearchPath" to "http://msdl.microsoft.com/download/symbols". If it crashes before you're able to attach the debugger, you should use our Release repo (with 0.17.4 not the insiders) https://github.com/Microsoft/vscode-cpptools/tree/release and set a breakpoint after the languageClient.start(); call and then attach a debugger to the crashing process....looks like I already said some of that in my previous response above :)

**Comment by ibousio** [comment]
After upgrade to 0.17.4 It seems Ok. No crashes anymore.

**Comment by lumonix** [comment]
I get this issue a lot in 0.19.0.
(Sometimes it happens every few seconds)

In my case I get it a lot while working with Pixar USD library related projects
Possible related to having two tabs side-by side where one tab has a file that is inside my project folder and another tab has a file from the USD GitHub repo.
But I have not tried to get an exact repro.

Is there a way to prevent the log from popping up when this crash happens?
(It happens so frequently that it makes it a bit hard to work)


[Error - 1:11:16 PM] Connection to server got closed. Server will not be restarted.
[Error - 1:11:16 PM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\kees1\.vscode\extensions\ms-vscode.cpptools-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:825:25)
	at Object.dispose (C:\Users\kees1\.vscode\extensions\ms-vscode.cpptools-0.19.0\node_modules\vscode-languageclient\lib\client.js:57:35)
	at LanguageClient.handleConnectionClosed (C:\Users\kees1\.vscode\extensions\ms-vscode.cpptools-0.19.0\node_modules\vscode-languageclient\lib\client.js:1864:38)
	at LanguageClient.handleConnectionClosed (C:\Users\kees1\.vscode\extensions\ms-vscode.cpptools-0.19.0\node_modules\vscode-languageclient\lib\main.js:106:15)
	at closeHandler (C:\Users\kees1\.vscode\extensions\ms-vscode.cpptools-0.19.0\node_modules\vscode-languageclient\lib\client.js:1852:18)
	at CallbackList.invoke (C:\Users\kees1\.vscode\extensions\ms-vscode.cpptools-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\kees1\.vscode\extensions\ms-vscode.cpptools-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (C:\Users\kees1\.vscode\extensions\ms-vscode.cpptools-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (C:\Users\kees1\.vscode\extensions\ms-vscode.cpptools-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\kees1\.vscode\extensions\ms-vscode.cpptools-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at StreamMessageReader.AbstractMessageReader.fireClose (C:\Users\kees1\.vscode\extensions\ms-vscode.cpptools-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:135:27)
	at Socket.<anonymous> (C:\Users\kees1\.vscode\extensions\ms-vscode.cpptools-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:188:62)
	at emitOne (events.js:101:20)
	at Socket.emit (events.js:191:7)
	at Pipe._handle.close [as _onclose] (net.js:510:12)

**Comment by sean-mcmanus** [comment]
@lumonix That error message is a just a symptom of the Microsoft.VSCode.CPP.Extension process crashing and doesn't contain enough info for us to diagnose. We need a repro or a call stack via attaching a debugger to the process before it crashes. Are you able to get us a call stack? Our Insider release at https://github.com/Microsoft/vscode-cpptools/releases/tag/0.19.1-insiders3 fixed at least one known crash:  https://github.com/Microsoft/vscode-cpptools/issues/2586 .

**Comment by lumonix** [comment]
@sean-mcmanus I've tried attaching  debugger on Windows, but the extension process crashes and the debugger detaches without giving a callstack I can give you.

If you have suggestions on how to get you a callstack, let me know.
The problem is very easy to reproduce on my end.

**Comment by sean-mcmanus** [comment]
What debugger are you using? If you're using the VS Code debugger, you need to set `"symbolSearchPath": "http://msdl.microsoft.com/download/symbols"` to get the symbols in the used config in the launch.json. If you're using VS 2017 you need to check the "Microsoft Symbol Servers" pdb locations. Can you try that?

**Comment by lumonix** [comment]
Hi @sean-mcmanus 

Still not luck getting a call-stack.
The debug output is minimal, but here it is:

The thread 4708 has exited with code 0 (0x0).
The thread 9124 has exited with code 0 (0x0).
Exception thrown at 0x743817D2 in Microsoft.VSCode.CPP.IntelliSense.Msvc.exe: Microsoft C++ exception: a_cfe_exception at memory location 0x039FF577.
The thread 1536 has exited with code 0 (0x0).
Loaded 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreei.dll'. Symbols loaded.
The thread 2208 has exited with code 0 (0x0).
The thread 7444 has exited with code 0 (0x0).
The thread 936 has exited with code 0 (0x0).
The program '[9956] Microsoft.VSCode.CPP.IntelliSense.Msvc.exe' has exited with code 0 (0x0).

**Comment by lumonix** [comment]
(I was attached to 9956 for what its worth)

**Comment by bobbrow** [comment]
Exiting with code 0 seems like a normal termination.  However, if the crash is in one of the `IntelliSense` processes, I would recommend installing the [Child Process Debugging extension](https://marketplace.visualstudio.com/items?itemName=vsdbgplat.MicrosoftChildProcessDebuggingPowerTool) for Visual Studio, and then attaching to `Microsoft.VSCode.CPP.Extension.exe` instead since it manages all of the language server processes.

**Comment by Botronicz** [comment]
I am having the same problem with cpptools.  It started occurring when I modified c_cpp_properties.json to include ""compileCommands": "build/compile_commands.json",".

I tried enabling the logging as suggested, but I get no log files.  But, I do get this error from the vscode "cpptools: <project name>" OUTPUT windows:

`[Error - 10:35:03 AM] Connection to server got closed. Server will not be restarted.
[Error - 10:35:03 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\khigbee\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\khigbee\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\khigbee\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-languageclient\lib\client.js:2150:42)
	at LanguageClient.handleConnectionClosed (C:\Users\khigbee\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-languageclient\lib\main.js:150:15)
	at closeHandler (C:\Users\khigbee\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-languageclient\lib\client.js:2137:18)
	at CallbackList.invoke (C:\Users\khigbee\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\khigbee\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\khigbee\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\khigbee\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\khigbee\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at StreamMessageReader.fireClose (C:\Users\khigbee\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at Socket.listen.readable.on (C:\Users\khigbee\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)`

**Comment by bobbrow** [comment]
@Botronicz, can you try the 0.22.0-insiders2 build?  We fixed a bug with shortened file paths that could be affecting you (we see this crash mostly with compile_commands.json users).

To enable it, set the `"C_Cpp.updateChannel"` setting to `"Insiders"`.

If that doesn't fix your problem, can you open a new issue with additional details about your crash?  (e.g. a sample entry from your compile_commands.json file, etc).

Thank you!

**Comment by kei2e** [comment]
Any solutions to this yet?
I have a similar issue: VSCode on Ubuntu 19.1, with C/C++ 0.26.1 extension installed. When I try to format a selected part of my code, I receive the error:

    [Error - 6:16:27 p.m.] Connection to server got closed. Server will not be restarted.
    [Error - 6:16:27 p.m.] Request textDocument/rangeFormatting failed.
