### ISSUE TITLE
C/C++ Intellisense process crashing

### ISSUE THREAD

**Issue by karera123** [microsoft/vscode-cpptools#2176]
Issue Type: <b>Bug</b>

Everytime I open vscode and edit a c/c++ file, intellisense doesn't work. When I check Task Manager, Microsoft.VSCode.CPP.Intellisense.Msvc.exe is not running.

Extension version: 0.17.5
VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.92GB (1.18GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sean-mcmanus** [comment]
We need more repro info. Are you saying that it's working before you do an edit? Are you able to attach a debugger before it crashes and then get a call stack of the crash location?

**Comment by karera123** [comment]
I don't know if this helps:
```
IntelliSense Engine = Default.
Autocomplete is enabled.
Error squiggles are enabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode
Code browsing service initialized
  Folder: C:/Users/John Nikko/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/7/include/ will be indexed
  Folder: C:/Users/John Nikko/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/local/include/ will be indexed
  Folder: C:/Users/John Nikko/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/ will be indexed
  Folder: C:/Users/John Nikko/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/ will be indexed
  Folder: C:/Users/John Nikko/Desktop/codes/ will be indexed
Discovering files...
  Processing folder (recursive): C:/Users/John Nikko/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/7/include/
  Processing folder (recursive): C:/Users/John Nikko/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/local/include/
  Processing folder (recursive): C:/Users/John Nikko/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/
  Processing folder (recursive): C:/Users/John Nikko/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/
  Processing folder (recursive): C:/Users/John Nikko/Desktop/codes/
  Discovering files: 2728 file(s) processed
  200 file(s) removed from database
Done discovering files.
Parsing remaining files...
  Parsing: 391 files(s) processed
Done parsing remaining files.
Failed to spawn IntelliSense process: Unable to start child process!
Shutting down IntelliSense server: C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Checking for syntax errors: file:///c%3A/Users/John%20Nikko/Desktop/codes/c/es5/sorted_sequence.c
Failed to spawn IntelliSense process: Unable to start child process!
Shutting down IntelliSense server: C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Failed to create IntelliSense client. Can't create intellisense client for C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Failed to spawn IntelliSense process: Unable to start child process!
Shutting down IntelliSense server: C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Failed to create IntelliSense client. Can't create intellisense client for C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Failed to spawn IntelliSense process: Unable to start child process!
Shutting down IntelliSense server: C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Failed to create IntelliSense client. Can't create intellisense client for C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Failed to spawn IntelliSense process: Unable to start child process!
Shutting down IntelliSense server: C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Failed to create IntelliSense client. Can't create intellisense client for C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Failed to spawn IntelliSense process: Unable to start child process!
Shutting down IntelliSense server: C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Failed to create IntelliSense client. Can't create intellisense client for C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Failed to spawn IntelliSense process: Unable to start child process!
Shutting down IntelliSense server: C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Failed to create IntelliSense client. Can't create intellisense client for C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Checking for syntax errors: file:///c%3A/Users/John%20Nikko/Desktop/codes/c/es5/sorted_sequence.c
Failed to spawn IntelliSense process: Unable to start child process!
Shutting down IntelliSense server: C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Failed to create IntelliSense client. Can't create intellisense client for C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Checking for syntax errors: file:///c%3A/Users/John%20Nikko/Desktop/codes/c/es5/sorted_sequence.c
Failed to spawn IntelliSense process: Unable to start child process!
Shutting down IntelliSense server: C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Failed to create IntelliSense client. Can't create intellisense client for C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Failed to query default include paths and defines for C:\Users\John Nikko\Documents\portable programs\Dev-Cpp 5.11\MinGW64\bin\g++.exe. WSL not detected
Checking for syntax errors: file:///c%3A/Users/John%20Nikko/Desktop/codes/c/es5/sorted_sequence.c
Using configuration: "MinGW"
Failed to query default include paths and defines for C:\Users\John Nikko\Documents\portable programs\Dev-Cpp 5.11\MinGW64\bin\g++.exe. WSL not detected
  Folder: C:/Users/John Nikko/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/7/include/ will be indexed
  Folder: C:/Users/John Nikko/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/local/include/ will be indexed
  Folder: C:/Users/John Nikko/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/ will be indexed
  Folder: C:/Users/John Nikko/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/ will be indexed
  Folder: C:/Users/John Nikko/Desktop/codes/ will be indexed
Failed to spawn IntelliSense process: Unable to start child process!
Shutting down IntelliSense server: C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Failed to create IntelliSense client. Can't create intellisense client for C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Discovering files...
  Processing folder (recursive): C:/Users/John Nikko/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/7/include/
  Processing folder (recursive): C:/Users/John Nikko/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/local/include/
  Processing folder (recursive): C:/Users/John Nikko/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/
  Processing folder (recursive): C:/Users/John Nikko/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/
Failed to spawn IntelliSense process: Unable to start child process!
Shutting down IntelliSense server: C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Failed to create IntelliSense client. Can't create intellisense client for C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Failed to spawn IntelliSense process: Unable to start child process!
Shutting down IntelliSense server: C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Failed to create IntelliSense client. Can't create intellisense client for C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
  Processing folder (recursive): C:/Users/John Nikko/Desktop/codes/
  Discovering files: 2728 file(s) processed
  8 file(s) removed from database
Done discovering files.
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
Failed to spawn IntelliSense process: Unable to start child process!
Shutting down IntelliSense server: C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Failed to create IntelliSense client. Can't create intellisense client for C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Failed to spawn IntelliSense process: Unable to start child process!
Shutting down IntelliSense server: C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Failed to create IntelliSense client. Can't create intellisense client for C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Failed to spawn IntelliSense process: Unable to start child process!
Shutting down IntelliSense server: C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Failed to create IntelliSense client. Can't create intellisense client for C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Checking for syntax errors: file:///c%3A/Users/John%20Nikko/Desktop/codes/c/es5/sorted_sequence.c
Failed to spawn IntelliSense process: Unable to start child process!
Shutting down IntelliSense server: C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
Failed to create IntelliSense client. Can't create intellisense client for C:\Users\John Nikko\Desktop\codes\c\es5\sorted_sequence.c
```

**Comment by bobbrow** [comment]
"Unable to start child process" is the message you get when `CreateProcessW` fails.  We might need to add additional logging for this case to figure out what's wrong.  You can try reinstalling the extension if this is a persistent error in all of your workspaces.

**Comment by sean-mcmanus** [comment]
I may have figured out the repro -- it repros for me when the intelliSenseMode is set to msvc-x64. Does changing it to clang-x64 or gcc-x64 fix this? If not, it's still possible the root cause is the same, i.e. fixing it for msvc-x64 might fix other scenarios. If not, it's still possible the root cause is the same, i.e. fixing it for msvc-x64 might fix other scenarios.

**Comment by karera123** [comment]
I think I found the cause of the problem. I think it's because there's a space in user folder name "John Nikko". When I tried to create another account without space in it (user folder without space), the c/cpp intellisense worked but when i created  another account with space in it, in the debug tab shows "failed to create child process..." something like that.

**Comment by butchiki** [comment]
> 
> 
> I may have figured out the repro -- it repros for me when the intelliSenseMode is set to msvc-x64. Does changing it to clang-x64 or gcc-x64 fix this? If not, it's still possible the root cause is the same, i.e. fixing it for msvc-x64 might fix other scenarios. If not, it's still possible the root cause is the same, i.e. fixing it for msvc-x64 might fix other scenarios.

**Comment by ghost** [comment]
@butchiki  Yea, that may be case. Coz I too have a space in my username where intellisense failed, although the target file(cpp) was in a different location(without any spaces).

**Comment by Angelo1211** [comment]
Having the same issue here, although it has only appeared in the last ~2 days or so. Could this possibly mean anything? I got it from the VSscode window log .

![image](https://user-images.githubusercontent.com/11263073/47963595-a075eb00-e02e-11e8-9404-2d4ec0222e12.png)

**Comment by DeepSeaDelight** [comment]
I'd like to add into here, as a layperson learning to code in C++ on Mac, every time XCode is updated by Apple and the update is installed, VS Code "forgets" where the includePath is after installation is complete... Almost as if it's forgetting the location of XCode's C++ libraries.

The directions to figure out how to fix that on my own are rather cryptic, especially for someone like myself that is learning how to really program.

This seems like something that should be fixed sooner rather than later...

**Comment by bobbrow** [comment]
@DeepSeaDelight, are you hardcoding the system include path into your configuration?  If you are using the `compilerPath` property to set your compiler (e.g. `"/usr/bin/clang"`) all you would need to do is reload the VS Code window to pick up the new compiler.  We don't detect if the compiler is updated out from under you right now.

**Comment by sean-mcmanus** [comment]
I'm not able to repro any bug when there's a space in my user name using WSL/gcc -- maybe there's some additional repro requirement?

**Comment by karera123** [comment]
I really don't know what's the real cause, but in my case, having a space in the user folder name makes the intellisense crash (can't create a child process). So my solution is to create a new account in Windows 10 without space in its user folder and now the intellisense works perfectly.

**Comment by Angelo1211** [comment]
I still don't have a fix for this issue but I thought I'd share my debug print, which is really similar to @butchiki's and highlight a line that stood out to me because the ///e%3A looked out of place. I have no idea if that's intended or not, but thought it might be worth sharing. I can try other stuff if you want help finding a way to repro this issue.

`Attempting to get defaults from compiler found on the machine: 'C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx64/x64/cl.exe'
  Folder: C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/VC/TOOLS/MSVC/14.15.26726/INCLUDE/* will be indexed
  Folder: C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/VC/TOOLS/MSVC/14.15.26726/ATLMFC/INCLUDE/* will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17134.0/UM/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17134.0/UCRT/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17134.0/SHARED/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17134.0/WINRT/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17134.0/CPPWINRT/ will be indexed
  Folder: C:/VS_DEV_LIB/ will be indexed
  Folder: E:/CPPPROJECTS/HYBRIDRENDERINGENGINE/ will be indexed
textDocument/didOpen
Discovering files...
  Processing folder (non-recursive): C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/VC/TOOLS/MSVC/14.15.26726/INCLUDE
  Processing folder (non-recursive): C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/VC/TOOLS/MSVC/14.15.26726/ATLMFC/INCLUDE
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17134.0/UM/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17134.0/UCRT/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17134.0/SHARED/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17134.0/WINRT/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17134.0/CPPWINRT/
  Processing folder (recursive): C:/VS_DEV_LIB/
  Processing folder (recursive): E:/CPPPROJECTS/HYBRIDRENDERINGENGINE/
`
**Checking for syntax errors: file:///e%3A/CppProjects/HybridRenderingEngine/include/texture.h**
`
textDocument/documentSymbol
  Discovering files: 7511 file(s) processed
  0 file(s) removed from database
Done discovering files.
Populate include completion cache.
Parsing open files...
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
Done parsing open files.
Failed to spawn process. Error: 193 ()
Failed to spawn IntelliSense process: Unable to start child process!
Shutting down IntelliSense server: E:\CPPPROJECTS\HYBRIDRENDERINGENGINE\SRC\TEXTURE.CPP
Failed to create IntelliSense client. Can't create intellisense client for E:\CPPPROJECTS\HYBRIDRENDERINGENGINE\INCLUDE\TEXTURE.H`

**Comment by sean-mcmanus** [comment]
@Angelo1211 The ///e%3A in the log is not a sign of a bug. The "Failed to spawn process. Error 193" means Windows is failing from "ERROR_BAD_EXE_FORMAT", "Microsoft.VSCode.CPP.IntelliSense.Msvc.exe is not a valid Win32 application". How did you install the extension? Could the binary be corrupted, i.e. from some partial download? Are you able to run that binary from the command line? Does uninstall/reinstall fix it? The main process Microsoft.VSCode.CPP.Extensions.exe is running correctly.

**Comment by Angelo1211** [comment]
@sean-mcmanus Hi, I downloaded the extension from the VSCode marketplace. I also tried installing / uninstalling and still get the same errors. I have also tried running the binary from the command line and it would execute and quit with no apparent errors. 

Apart from that I've tried running multiple different C++ projects in VSCode with the same results. I also tried running those same projects on visual studio 2017 and the intellisense there worked fine. Also tried to disable every extension except this one and still had the error occur.

**Comment by Angelo1211** [comment]
@sean-mcmanus So I also tried making two new users, one with and another without a space and in both cases intellisense worked fine with no crashes. Since there was a chance the binary was corrupted I copied the binaries I knew were working from a new user to the admin and still got the same error (193). 

I've also tried 0.21.0-insiders installed through the vsix and 0.20.1 with the same issues on the Admin user but no issues on the new ones. Is there anything else you think I could try that might shed some light on this? Thanks!

**Comment by sean-mcmanus** [comment]
@Angelo1211 So there's some bug when using the Admin account? Yeah, I don't know what could be causing that. Maybe that could happen if some path has the Windows case sensitive file system enabled.

**Comment by Angelo1211** [comment]
@sean-mcmanus So I've checked to see if the case sensitivity property was enabled recursively for all folders in all of my project files, user folders, .vscode folder and visual studio 2017 folder and it wasn't active in any of them. 

In any case, I have found a relatively painless workaround that re-enables intellisense and lets you keep using your extensions & setttings without having to leave your admin account . 

1. Make a new user
2. Still in your admin account, copy your .vscode folder from `C:\users\<admin> to C:\users\<newUser>`
3. Also from admin, run vscode from the command line with this command:
 `
code --extensions-dir C:\Users\<newUser>\.vscode\extensions
` 

And that should make it work again. Although it's not great since now I have a new windows user I don't want/need but it's better than no intellisense at all.  It's definitely some path issue related to the location of the extensions folder but I have not been able to pinpoint it any further. Hope this helps someone though!

**Comment by kckemper** [comment]
It seems that if you move the extensions folder even to just C:\.vscode\extensions it works. No need to create a new user.

**Comment by bkh751** [comment]
in my case, I had a crash when I had directory name not written in English.
So when I changed it to english, it solved

**Comment by sean-mcmanus** [comment]
The bug with IntelliSense not working on Windows when the username has a space in it should be fixed with 0.22.0-insiders2: https://github.com/Microsoft/vscode-cpptools/releases .
