### ISSUE TITLE
Code outline does not work on remote ssh filesystem

### ISSUE THREAD

**Issue by andy-z** [microsoft/vscode-cpptools#2974]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Win10 Pro
- VS Code Version: 1.30.1
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them): SSH FS, Python
- Code Outline does not show anything at all for C++ files open on remote filesystem using SSH protocol (`ssh://` prefix)

**To Reproduce**

1. Connect to remote filesystem using SSH protocol (e.g. using kelvin.vscode-sshfs extension)
2. Open any C++ file
3. Outline panel shows text "There are no editors open that can provide outline information"

**Expected behavior**
Outline view should show symbols from currently open C++ file

**Additional context**
I opened an issue against VSCode originally but they claim it's an extension issue: https://github.com/Microsoft/vscode/issues/65752

**Comment by welblaud** [comment]
The same for PHP:

- local OS: Ubuntu 19.10
- remote OS: Debian 10
- VS Code version: 1.40.2
- PHP Extension Pack version: 1.0.2

**UPDATE**
During writing this message, the outline has appeared. It seems it was necessary to let the IDE build some index. It seems solved now.

**Comment by azavor** [comment]
It still does not work on C/C++ extension version 1.1.0 both for MacOS Catalina and Fedora 33 VS Code version 1.51.0, remote SSH extension 0.55.0. Only OUTLINE panel shows now text "The active editor cannot provide outline information".

**Comment by azavor** [comment]
With C/C++ extension 1.1.1, SSH extension 0.56.0, and VS Code 1.51.1 code outline now works. Not sure which update fixed it.

**Comment by sean-mcmanus** [comment]
@azavor 1.1.1 only fixed https://github.com/microsoft/vscode-cpptools/issues/6453, so unlikely to fix this issue. It's possible a dangling cpptools process was locking the database, which could cause the outline to not work.
