### ISSUE TITLE
Include file not found in include directory

### ISSUE THREAD

**Issue by Kurt-Shiwz** [microsoft/vscode-cpptools#310]
Can't include boost header.
vs code: 1.6.1
cpptools: 0.9.2
os: macOS 10.12.1
boost:1.62 (install by brew)
![vscode](https://cloud.githubusercontent.com/assets/7554917/19725358/a670d28a-9bb7-11e6-89d5-fd60ec6384fa.png)

**Comment by OptSolution** [comment]
I also met the problem, do you fix it?
![2016-11-13 21-36-51](https://cloud.githubusercontent.com/assets/18118718/20246050/896f8b50-a9e9-11e6-8b90-43bffc21e2bd.png)

**Comment by Kurt-Shiwz** [comment]
No, Still waiting

**Comment by OptSolution** [comment]
I fixed it, the error in my VSCode was from "C/C++ Clang", not from the plugin

**Comment by Kurt-Shiwz** [comment]
Can you tell me what you did

**Comment by OptSolution** [comment]
My error was from the plugin, "C/C++ Clang". I think yours is from "C/C++", you can install "C/C++ Clang" to help you complete codes and check, but it can't help you peek definition or go to definition.

**Comment by Kurt-Shiwz** [comment]
find feference disappear, don't have loading prompt and this bug still here...

**Comment by sean-mcmanus** [comment]
Do you have the C/C++ extension installed? Is the platform text red in the bottom right?

**Comment by Kurt-Shiwz** [comment]
![2016-12-29 22 08 16](https://cloud.githubusercontent.com/assets/7554917/21545524/70ae19c6-ce13-11e6-8288-7ac7f9a7797e.jpg)
![2016-12-29 22 02 44](https://cloud.githubusercontent.com/assets/7554917/21545527/7129221a-ce13-11e6-8510-bec5583ca333.jpg)
![2016-12-29 21 58 35](https://cloud.githubusercontent.com/assets/7554917/21545526/71272f5a-ce13-11e6-8a76-41fdc6b50aea.jpg)
![2016-12-29 21 57 07](https://cloud.githubusercontent.com/assets/7554917/21545525/7126ce66-ce13-11e6-8fcf-a42fb8308343.jpg)
![2016-12-29 21 55 51](https://cloud.githubusercontent.com/assets/7554917/21545528/71628488-ce13-11e6-8d9a-8d271549a182.jpg)
@sean-mcmanus

**Comment by sean-mcmanus** [comment]
Thanks for reporting these issues. Autocomplete for headers inside #include doesn't work currently. The goto definition for extensionless headers uses a fixed list and "boost" is not in that list (string is). We'll investigate fixing these issues later.

**Comment by cfstras** [comment]
Another hint for people suffering from this: I accidentally had both the "C/C++", and the "C++ Intellisense" extensions installed. Disabling the latter fixed it for me.

**Comment by jankap** [comment]
I can confirm this answer. I had C++ Intellisense installed too, but disabled. Uninstalling solved it though!

**Comment by sean-mcmanus** [comment]
Yes, we fixed it so extensionless headers can be found and go to definition from the header should open the file and associate it with C++ (autocomplete and quickinfo in #include still doesn't work well).

**Comment by bobbrow** [comment]
These issues should be fixed in the latest version of the extension.  Please let us know if they are not.

**Comment by felixWangZQ** [comment]
I have the same problem with the version 0.11.0. I simply add the same path to 'browse/path' and the error message disappear. So I think this problem is caused by undefined browse path. 
I do not know the root cause. It just gets rid of the ignoring message. Hope it could help others with similar problem.
