### ISSUE TITLE
Format document causes language server to shut down

### ISSUE THREAD

**Issue by renkun-ken** [microsoft/vscode-cpptools#3559]
**Type: LanguageService**

When I format a cpp document in a cmake project, the language server seems to shut down. Following is the log produced by `cpptools`:

```
[Error - 11:54:44 PM] Connection to server got closed. Server will not be restarted.
[Error - 11:54:44 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-languageclient/lib/client.js:2150:42)
	at LanguageClient.handleConnectionClosed (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-languageclient/lib/main.js:150:15)
	at closeHandler (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-languageclient/lib/client.js:2137:18)
	at CallbackList.invoke (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at StreamMessageReader.fireClose (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.listen.readable.on (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)
[Error - 11:54:44 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-languageclient/lib/client.js:2150:42)
	at LanguageClient.handleConnectionClosed (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-languageclient/lib/main.js:150:15)
	at closeHandler (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-languageclient/lib/client.js:2137:18)
	at CallbackList.invoke (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at StreamMessageReader.fireClose (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.listen.readable.on (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)
[Error - 11:54:44 PM] Request textDocument/formatting failed.
Error: Connection got disposed.
	at Object.dispose (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-languageclient/lib/client.js:2150:42)
	at LanguageClient.handleConnectionClosed (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-languageclient/lib/main.js:150:15)
	at closeHandler (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-languageclient/lib/client.js:2137:18)
	at CallbackList.invoke (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at StreamMessageReader.fireClose (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.listen.readable.on (/home/ken/.vscode/extensions/ms-vscode.cpptools-0.23.0-insiders/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)
```

**Describe the bug**
- OS and Version: Ubuntu 19.04
- VS Code Version: 1.33.1
- C/C++ Extension Version: both 0.23.0-insiders and 0.22.1 release

**Comment by sean-mcmanus** [comment]
We're not aware of any crash like this. Can you attach a debugger to the Microsoft.VSCode.CPP.Extension.linux process before it crashes and get a call stack?

Does this repro in any file for you?

We haven't tested with Ubuntu 19 yet, could be some issue there.

What failure message do you see when you [enable Debug logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) ?

**Comment by sean-mcmanus** [comment]
We fixed some crashes with 0.23.0-insiders2 https://github.com/Microsoft/vscode-cpptools/releases/tag/0.23.0-insiders2 .

**Comment by ghost** [comment]
Same issue.

OS and Version : Ubuntu 19.04
VSCode Version : 1.36.1

**Comment by PavelCherniavskyi** [comment]
Same issue!
Ubuntu 19.04
VSCode Version : 0.24.1

**Comment by renkun-ken** [comment]
Crash no longer occurs with the latest release.

**Comment by ZweiEuro** [comment]
I just updated and the Error still occures for me
![pretty_error](https://user-images.githubusercontent.com/18036573/65878880-58bb2900-e38f-11e9-881d-62187f5a8228.png)

**Comment by renkun-ken** [comment]
Maybe there are different problems. I'll leave it open for now.

**Comment by jarodwen** [comment]
*UPDATED* Seems this can be fixed by specifying the clang-format path in the settings. 

See this issue after updating vscode this morning to 1.39.2; on fedora 30:

```
[Error - 2:32:46 PM] Connection to server got closed. Server will not be restarted.
[Error - 2:32:46 PM] Request textDocument/formatting failed.
Error: Connection got disposed.
	at Object.dispose (/home/uuser/.vscode/extensions/ms-vscode.cpptools-0.26.0/dist/main.js:2940:25)
	at Object.dispose (/home/usuer/.vscode/extensions/ms-vscode.cpptools-0.26.0/dist/main.js:3410:35)
	at LanguageClient.handleConnectionClosed (/home/uuser/.vscode/extensions/ms-vscode.cpptools-0.26.0/dist/main.js:5492:42)
	at LanguageClient.handleConnectionClosed (/home/uuser/.vscode/extensions/ms-vscode.cpptools-0.26.0/dist/main.js:15222:15)
	at closeHandler (/home/uuser/.vscode/extensions/ms-vscode.cpptools-0.26.0/dist/main.js:5479:18)
	at CallbackList.invoke (/home/uuser/.vscode/extensions/ms-vscode.cpptools-0.26.0/dist/main.js:10256:39)
	at Emitter.fire (/home/uuser/.vscode/extensions/ms-vscode.cpptools-0.26.0/dist/main.js:10314:36)
	at closeHandler (/home/uuser/.vscode/extensions/ms-vscode.cpptools-0.26.0/dist/main.js:2290:26)
	at CallbackList.invoke (/home/uuser/.vscode/extensions/ms-vscode.cpptools-0.26.0/dist/main.js:10256:39)
	at Emitter.fire (/home/uuser/.vscode/extensions/ms-vscode.cpptools-0.26.0/dist/main.js:10314:36)
	at StreamMessageReader.fireClose (/home/uuser/.vscode/extensions/ms-vscode.cpptools-0.26.0/dist/main.js:13089:27)
	at Socket.readable.on (/home/uuser/.vscode/extensions/ms-vscode.cpptools-0.26.0/dist/main.js:13129:46)
	at Socket.emit (events.js:187:15)
	at Pipe._handle.close (net.js:606:12)
```

Here are the vscode version information:

```
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.2.17-200.fc30.x86_64
```

CPP plugin is 0.26.0

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity and suggested solution.
