### ISSUE TITLE
C++ syntax highlighting incorrect for variable instance

### ISSUE THREAD

**Issue by sweettyler** [microsoft/vscode-cpptools#4109]
Please see https://github.com/microsoft/vscode/issues/79520 for detail.

**Comment by sweettyler** [comment]
Same problem even with the latest version 0.25.0-insiders2.

**Comment by Colengms** [comment]
Hi @sweettyler .  I'm unable to reproduce the issue with the information provided.  If I add a minimal class to allow the code you posted to the other thread to compile, I get the following:

![image](https://user-images.githubusercontent.com/49173979/63369790-8c894480-c335-11e9-97fe-5578a3d7a87e.png)

There must be something about other code being parsed that is leading to an issue.  Could you provide a complete repro?

I'd suggest looking previously in the file for error squiggles and resolving them.  That might clear up whatever is confusing the parser.

**Comment by Colengms** [comment]
Actually, based the image you posted, it looks like your code started on line 1 without defining myFile.  Are you using a forced include?  I would at least expect to see squiggles due to myFile not being defined.

**Comment by sweettyler** [comment]
Hi @Colengms You are right - if you have defined the class "myFile" then you cannot reproduce what I said. I happened to notice this issue as I first started writing the main() and at that time the class "myFile" was not ready yet. However, my point is, the two variables, "myInput" and "myOuput" should not be highlighted in different colours (not matter the class "myFile" is defined or not).

**Comment by Colengms** [comment]
I also cannot repro an issue with this as the only content.  Rather, I see:

![image](https://user-images.githubusercontent.com/49173979/63378628-800de780-c347-11e9-9d83-51ac7c58a588.png)

VS Code provides syntactic colorization (TextMate grammar rules).  The C/C++ extension adds semantic colorization over that.  Semantic colorization is based on having essentially compiled the file to determine context.  If the code does not compile, it would be by-design if some semantic colorization were not applied.  You might try confirming whether semantic colorization is involved in your repro by disabling it (by setting C_Cpp.enhancedColorization to Disabled).  If you are still seeing an issue without semantic colorization enabled, it would be an issue with syntactic colorization, and you might want to pursue that with the issue you have open against VS Code.

**Comment by sweettyler** [comment]
Hi @Colengms it seems to be related with semantic colorization. If I disable it then "myInput" and "myOuput" are all in white. I still don't have these squiggles, but I think it may appear if I enable or disable some other settings.

**Comment by sweettyler** [comment]
I also found another small bug, to reproduce it:
1) set "C_Cpp: Enhanced Colorization" to "enabled";
2) make sure "new_file.cc" doesn't exist;
3) type "code new_test_file.cc" and press "enter";
3) copy the five lines of my example code to the VScode window, and press "ctrl+s" to save it;
4) notice at this step "myInput" is in white (see attached screenshot);
5) exit VScode;
6) type "code new_file.cc" again and press "enter";
7) notice this time "myInput" changes to cyan (see attached screenshot);
![snapshot1](https://user-images.githubusercontent.com/49961658/63382663-c3c11b00-c360-11e9-9afd-b138630a0d14.png)
![snapshot2](https://user-images.githubusercontent.com/49961658/63382671-c6bc0b80-c360-11e9-99db-774613a3acab.png)

**Comment by sweettyler** [comment]
so relaunching VScode makes some difference.

**Comment by sean-mcmanus** [comment]
Your repro steps match https://github.com/microsoft/vscode-cpptools/issues/4091 so the root cause could be the same, i.e. creating a new file and saving it will cause our underlying document object to have duplicate results, which can be shown via formatting, but it may also break IntelliSense-based stuff (fix should be in our pending 0.25.0 release).

**Comment by matter123** [comment]
@sean-mcmanus I can reproduce even if I run `pkill code` (which terminates any Microsoft.VSCode.CPP.* processes) and open a fresh copy of vscode.

**Comment by sean-mcmanus** [comment]
@matter123 You repro what exactly? The bug I was referring to in https://github.com/microsoft/vscode-cpptools/issues/4109#issuecomment-523194347 could be caused by a TypeScript issue which could repro repeatedly with a new language server process (following the repro steps at https://github.com/microsoft/vscode-cpptools/issues/4109#issuecomment-523185567 ).

**Comment by matter123** [comment]
that `myInput` is colored cyan.

In particular, my steps are:
1. Completely close vscode
2. In another editor, save the contents to a new `.cpp` file
3. run `code /path/to/new/file.cpp`
4. Observe that `myInput` becomes colored cyan.

**Comment by Colengms** [comment]
There is currently a known issue ( https://github.com/microsoft/vscode-cpptools/issues/4091 ) with incorrect behavior after having just launched VS with a new file, which is addressed in the next release (pending).

The issue with having only 1 of the 2 variable instances properly colored is by-design, as semantic colorization depends on essentially compiling the file, and the file is not in a compilable state.  It can infer to a limited extent, but after failing to parse the first call to myFile() as a function, it ceases to make the same assumption that myFile is a type for the rest of the file.

![image](https://user-images.githubusercontent.com/49173979/63390134-dccacb80-c362-11e9-9c8b-1ff10b47c86a.png)

**Comment by sweettyler** [comment]
Semantic colorization exists in several editors and IDEs, like Sublime Text 3 and Eclipse. For the example code, both Sublime Text 3 and Eclipse don't behave as same as VScode does. If this is by design, I think at least some fine-tune is needed.

**Comment by Colengms** [comment]
The Intellisense (and semantic colorization) in the VS Code C/C++ extension is based on code shared from Visual Studio.  Visual Studio shows the same result:

![image](https://user-images.githubusercontent.com/49173979/63453449-8bbbe580-c3fd-11e9-8e3e-16a1955d7fb9.png)

I've opened a feedback item for your issue against VS.  It is [here](https://developercommunity.visualstudio.com/content/problem/703793/c-semantic-colorization-incorrect-for-variable-ins.html
) if you'd like to upvote it.

**Comment by sweettyler** [comment]
The second reported issue may have nothing to do with  #4091 - after I installed the latest cpptool-0.25.0 and could still reproduce the issue.

**Comment by sean-mcmanus** [comment]
@sweettyler -- yeah, looks like the fix didn't work 100%, see https://github.com/microsoft/vscode/issues/79252#issuecomment-525025641 .

**Comment by Colengms** [comment]
The secondary issue (no colorization in newly saved file) should be addressed by https://github.com/microsoft/vscode-cpptools/pull/4153 .

**Comment by s4ln1x** [comment]
Hi, I think I found a C syntax highlighting issue, should I post here the information or should I create another issue?, P.D. I reach this issue from searching in the issues bar.

**Comment by Colengms** [comment]
Hi @reycobra .  It may depend on what is highlighting incorrectly.  The C/C++ extension adds semantic colorization, but the basic syntactic colorization is coming from VS Code and the TextMate grammar for C/C++.  One way to find out which is involved would be to disable the setting "C_Cpp.EnhancedColorization".  If the issue is still present with that disabled, it would seem to be an issue with the TextMate grammar, which I'd suggesting opening an issue for at https://github.com/jeff-hykin/cpp-textmate-grammar .  (Jeff contributes this grammar to VS Code).  If the issue is not present with that setting disabled, I'd suggest opening an issue here in vscode-cpptools to discuss it.

**Comment by s4ln1x** [comment]
Hi @Colengms, thanks for answering!!, the issue is still present after I disabled the setting "C_Cpp.EnhancedColorization", so I will check the issues in the repository you suggested me and if nothing similar to what I'm seeing is happening I will open a new issue there. Thanks again!!!

**Comment by sean-mcmanus** [comment]
@prabhavagrawal7 I'm not able to repro the issue. Can you file a new bug with more repro details, such as the output of running C/C++: Log Diagnostics and your C_Cpp.enhancedColorization setting?

**Comment by sean-mcmanus** [comment]
@prabhavagrawal7 I reproed the issue now -- our IntelliSense parser is returning incorrect semantic tokens, perhaps due to the usage of the templates. I'll move this to a new issue.

**Comment by bobbrow** [comment]
The feedback ticket tracking the issue originally tracked by this issue was closed without a fix. Unfortunately, this means that a fix will not be coming to VS Code either. A few other potential bugs were mentioned in this issue. If they have not been addressed, please open a new issue and we can take a look.
