### ISSUE TITLE
"identifier is undefined" despite being found (only Linux/gcc, not macOS)

### ISSUE THREAD

**Issue by slhck** [microsoft/vscode-cpptools#7326]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 20.04
- VS Code Version: Version: 1.55.1
- C/C++ Extension Version: v1.3.0-insiders5
- Other extensions you installed (and if the issue persists after disabling them): N/A
- Does this issue involve using SSH remote to run the extension on a remote machine?: Yes
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

I have a project using the `loguru` library which I compile with meson. The `include` directory contains:

```
include
├── loguru
│   ├── loguru.cpp
│   └── loguru.hpp
```

In my C++ file, I add:

```
#define LOGURU_WITH_STREAMS 1
#include <loguru.cpp>
```

and use the function `LOG_S`, e.g.

```c++
LOG_S(INFO) << "Connected to Redis server at " << host << ":" << port;
```

Under Linux, connected to a remote server, it shows the following error:

![image](https://user-images.githubusercontent.com/582444/114170759-a83ec580-9933-11eb-891c-15d4b856e154.png)

Under macOS, this error does not appear! Both are using the same settings and meson config.

What is interesting is that this used to work on both machines, so perhaps it was related to a recent change. I haven't changed any build or include settings.

Also, it is apparently able to resolve the definition of the function, but still shows the error? (See screenshot.)

I have tried applying latest updates and reloading the respective VS Code window.

I have tried creating a new test file, but there, the error does not appear, so I cannot really provide a reproducible example.

----

## Details

`c_cpp_properties.json`:

```json
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "macFrameworkPath": [],
            "compilerPath": "/usr/local/bin/gcc-10",
            "cStandard": "gnu17",
            "intelliSenseMode": "macos-gcc-x64",
            "compileCommands": "${workspaceFolder}/builddir/compile_commands.json",
            "compilerArgs": [],
            "cppStandard": "c++17",
            "browse": {
                "path": [
                    "${workspaceFolder}/**"
                ],
                "limitSymbolsToIncludedHeaders": true
            }
        },
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "gnu17",
            "intelliSenseMode": "linux-gcc-x64",
            "compileCommands": "${workspaceFolder}/builddir/compile_commands.json",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}
```

`compile_commands.json`:

```json
[
  {
    "directory": "/home/werner/Documents/Projects/test/test-latency/builddir",
    "command": "c++ -Isrc/test_utils/libtest_utils.so.p -Isrc/test_utils -I../src/test_utils -I../include/loguru -I../include/test -I../include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -g -fPIC -pthread -MD -MQ src/test_utils/libtest_utils.so.p/test_utils.cpp.o -MF src/test_utils/libtest_utils.so.p/test_utils.cpp.o.d -o src/test_utils/libtest_utils.so.p/test_utils.cpp.o -c ../src/test_utils/test_utils.cpp",
    "file": "../src/test_utils/test_utils.cpp",
    "output": "src/test_utils/libtest_utils.so.p/test_utils.cpp.o"
  },
  {
    "directory": "/home/werner/Documents/Projects/test/test-latency/builddir",
    "command": "c++ -Isrc/test_test_latency.p -Isrc -I../src -I../include/test -I../include/redis-cpp -I../include/loguru -I../include/readerwriterqueue -I../include -Isrc/test_utils -I../src/test_utils -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -g -pthread -MD -MQ src/test_test_latency.p/test_test_latency.cpp.o -MF src/test_test_latency.p/test_test_latency.cpp.o.d -o src/test_test_latency.p/test_test_latency.cpp.o -c ../src/test_test_latency.cpp",
    "file": "../src/test_test_latency.cpp",
    "output": "src/test_test_latency.p/test_test_latency.cpp.o"
  },
  {
    "directory": "/home/werner/Documents/Projects/test/test-latency/builddir",
    "command": "c++ -Isrc/test_test_send_video.p -Isrc -I../src -I../include/test -I../include/redis-cpp -I../include/loguru -I../include/readerwriterqueue -I../include -Isrc/test_utils -I../src/test_utils -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -g -pthread -MD -MQ src/test_test_send_video.p/test_test_send_video.cpp.o -MF src/test_test_send_video.p/test_test_send_video.cpp.o.d -o src/test_test_send_video.p/test_test_send_video.cpp.o -c ../src/test_test_send_video.cpp",
    "file": "../src/test_test_send_video.cpp",
    "output": "src/test_test_send_video.p/test_test_send_video.cpp.o"
  },
  {
    "directory": "/home/werner/Documents/Projects/test/test-latency/builddir",
    "command": "c++ -Isrc/redis_test.p -Isrc -I../src -I../include/test -I../include/redis-cpp -I../include/loguru -I../include/readerwriterqueue -I../include -Isrc/test_utils -I../src/test_utils -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -g -pthread -MD -MQ src/redis_test.p/redis_test.cpp.o -MF src/redis_test.p/redis_test.cpp.o.d -o src/redis_test.p/redis_test.cpp.o -c ../src/redis_test.cpp",
    "file": "../src/redis_test.cpp",
    "output": "src/redis_test.p/redis_test.cpp.o"
  },
  {
    "directory": "/home/werner/Documents/Projects/test/test-latency/builddir",
    "command": "c++ -Isrc/test_latency_source.p -Isrc -I../src -I../include/test -I../include/redis-cpp -I../include/loguru -I../include/readerwriterqueue -I../include -Isrc/test_utils -I../src/test_utils -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -g -pthread -MD -MQ src/test_latency_source.p/test_latency_source.cpp.o -MF src/test_latency_source.p/test_latency_source.cpp.o.d -o src/test_latency_source.p/test_latency_source.cpp.o -c ../src/test_latency_source.cpp",
    "file": "../src/test_latency_source.cpp",
    "output": "src/test_latency_source.p/test_latency_source.cpp.o"
  },
  {
    "directory": "/home/werner/Documents/Projects/test/test-latency/builddir",
    "command": "c++ -Isrc/test_latency_receive.p -Isrc -I../src -I../include/test -I../include/redis-cpp -I../include/loguru -I../include/readerwriterqueue -I../include -Isrc/test_utils -I../src/test_utils -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -g -pthread -MD -MQ src/test_latency_receive.p/test_latency_receive.cpp.o -MF src/test_latency_receive.p/test_latency_receive.cpp.o.d -o src/test_latency_receive.p/test_latency_receive.cpp.o -c ../src/test_latency_receive.cpp",
    "file": "../src/test_latency_receive.cpp",
    "output": "src/test_latency_receive.p/test_latency_receive.cpp.o"
  }
]
```

<details>
  <summary><strong>Logs</strong></summary>

```
-------- Diagnostics - 4/9/2021, 1:04:58 PM
Version: 1.3.0-insiders5
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "gnu17",
    "intelliSenseMode": "linux-gcc-x64",
    "compileCommands": "${workspaceFolder}/builddir/compile_commands.json",
    "cppStandard": "c++17",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/werner/Documents/Projects/test/test-latency/src/test_latency_source.cpp ]:
    /home/werner/Documents/Projects/test/test-latency/src/test_latency_source.cpp
Translation Unit Configurations:
[ /home/werner/Documents/Projects/test/test-latency/src/test_latency_source.cpp ]:
    Process ID: 3887078
    Memory Usage: 513 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /home/werner/Documents/Projects/test/test-latency/builddir/src/test_latency_source.p
        /home/werner/Documents/Projects/test/test-latency/builddir/src
        /home/werner/Documents/Projects/test/test-latency/src
        /home/werner/Documents/Projects/test/test-latency/include/test
        /home/werner/Documents/Projects/test/test-latency/include/redis-cpp
        /home/werner/Documents/Projects/test/test-latency/include/loguru
        /home/werner/Documents/Projects/test/test-latency/include/readerwriterqueue
        /home/werner/Documents/Projects/test/test-latency/include
        /home/werner/Documents/Projects/test/test-latency/builddir/src/test_utils
        /home/werner/Documents/Projects/test/test-latency/src/test_utils
        /usr/include/c++/10
        /usr/include/x86_64-linux-gnu/c++/10
        /usr/include/c++/10/backward
        /usr/lib/gcc/x86_64-linux-gnu/10/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Defines:
        _FILE_OFFSET_BITS=64
    Standard Version: c++17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=100200
    compile_commands.json entry:
        directory: /home/werner/Documents/Projects/test/test-latency/builddir
        file: ../src/test_latency_source.cpp
        command: c++ -Isrc/test_latency_source.p -Isrc -I../src -I../include/test -I../include/redis-cpp -I../include/loguru -I../include/readerwriterqueue -I../include -Isrc/test_utils -I../src/test_utils -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -g -pthread -MD -MQ src/test_latency_source.p/test_latency_source.cpp.o -MF src/test_latency_source.p/test_latency_source.cpp.o.d -o src/test_latency_source.p/test_latency_source.cpp.o -c ../src/test_latency_source.cpp
        output: src/test_latency_source.p/test_latency_source.cpp.o
Total Memory Usage: 513 MB
Browse Paths from compile_commands.json, from workspace folder: /home/werner/Documents/Projects/test/test-latency
    /home/werner/Documents/Projects/test/test-latency/builddir
    /home/werner/Documents/Projects/test/test-latency/builddir/src
    /home/werner/Documents/Projects/test/test-latency/builddir/src/test_latency_receive.p
    /home/werner/Documents/Projects/test/test-latency/builddir/src/test_latency_source.p
    /home/werner/Documents/Projects/test/test-latency/builddir/src/test_test_latency.p
    /home/werner/Documents/Projects/test/test-latency/builddir/src/test_test_send_video.p
    /home/werner/Documents/Projects/test/test-latency/builddir/src/test_utils
    /home/werner/Documents/Projects/test/test-latency/builddir/src/test_utils/libtest_utils.so.p
    /home/werner/Documents/Projects/test/test-latency/builddir/src/redis_test.p
    /home/werner/Documents/Projects/test/test-latency/include
    /home/werner/Documents/Projects/test/test-latency/include/loguru
    /home/werner/Documents/Projects/test/test-latency/include/test
    /home/werner/Documents/Projects/test/test-latency/include/readerwriterqueue
    /home/werner/Documents/Projects/test/test-latency/include/redis-cpp
    /home/werner/Documents/Projects/test/test-latency/src
    /home/werner/Documents/Projects/test/test-latency/src/test_utils

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 24248
Number of files parsed: 1


```

```
cpptools/didChangeCppProperties
Attempting to get defaults from C compiler in "compilerPath" property: '/usr/bin/gcc'
Querying compiler for default C++ language standard using command line: "/usr/bin/gcc" -x c++ -E -dM /dev/null
terminating child process: 3891202
Detected language standard version: gnu++14
Querying compiler for default C language standard using command line: "/usr/bin/gcc" -x c -E -dM /dev/null
terminating child process: 3891207
Detected language standard version: gnu17
Querying compiler's default target using command line: "/usr/bin/gcc" -dumpmachine
Compiler returned default target value: x86_64-linux-gnu

terminating child process: 3891211
Compiler query command line: "/usr/bin/gcc" -std=gnu17 -Wp,-v -E -dD -x c -m64  /dev/null
terminating child process: 3891212
Code browsing service initialized
Attempting to get defaults from C++ compiler in "compilerPath" property: '/usr/bin/gcc'
Compiler query command line: "/usr/bin/gcc" -std=c++17 -Wp,-v -E -dD -x c++ -m64  /dev/null
terminating child process: 3891216
Attempting to get defaults from C++ compiler in "compilerPath" property: '/usr/bin/gcc'
Attempting to get defaults from C++ compiler in "compilerPath" property: '/usr/bin/gcc'
Attempting to get defaults from C++ compiler in "compilerPath" property: '/usr/bin/gcc'
Attempting to get defaults from C++ compiler in "compilerPath" property: '/usr/bin/gcc'
Attempting to get defaults from C++ compiler in "compilerPath" property: '/usr/bin/gcc'
Attempting to get defaults from C++ compiler in "compilerPath" property: '/usr/bin/gcc'
  Folder: /usr/include/ will be indexed
  Folder: /usr/lib/gcc/x86_64-linux-gnu/10/include/ will be indexed
  Folder: /usr/local/include/ will be indexed
  Folder: /home/werner/Documents/Projects/test/test-latency/builddir/ will be indexed
  Folder: /home/werner/Documents/Projects/test/test-latency/include/ will be indexed
  Folder: /home/werner/Documents/Projects/test/test-latency/src/ will be indexed
Populate include completion cache.
Discovering files...
  Processing folder (recursive): /usr/include/
cpptools/fileCreated: file:///home/werner/Documents/Projects/test/test-latency/builddir/src/log_test.p
  Processing folder (recursive): /usr/lib/gcc/x86_64-linux-gnu/10/include/
  Processing folder (recursive): /usr/local/include/
  Processing folder (recursive): /home/werner/Documents/Projects/test/test-latency/builddir/
  Processing folder (recursive): /home/werner/Documents/Projects/test/test-latency/include/
  Processing folder (recursive): /home/werner/Documents/Projects/test/test-latency/src/
  Discovering files: 24247 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
cpptools/didChangeCompileCommands: file:///home/werner/Documents/Projects/test/test-latency/builddir/compile_commands.json
cpptools/didChangeCompileCommands: file:///home/werner/Documents/Projects/test/test-latency/builddir/compile_commands.json
cpptools/getCodeActions: file:///home/werner/Documents/Projects/test/test-latency/src/test_latency_source.cpp (id: 2)
textDocument/didOpen: file:///home/werner/Documents/Projects/test/test-latency/src/test_latency_source.cpp
Attempting to get defaults from C++ compiler in "compilerPath" property: '/usr/bin/gcc'
cpptools/activeDocumentChange: file:///home/werner/Documents/Projects/test/test-latency/src/test_latency_source.cpp
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: file:///home/werner/Documents/Projects/test/test-latency/src/test_latency_source.cpp (id: 3)
cpptools/getDocumentSymbols
cpptools/textEditorSelectionChange
setestng compilation args for /home/werner/Documents/Projects/test/test-latency/src/test_latency_source.cpp
  include: /home/werner/Documents/Projects/test/test-latency/builddir/src/test_latency_source.p
  include: /home/werner/Documents/Projects/test/test-latency/builddir/src
  include: /home/werner/Documents/Projects/test/test-latency/src
  include: /home/werner/Documents/Projects/test/test-latency/include/test
  include: /home/werner/Documents/Projects/test/test-latency/include/redis-cpp
  include: /home/werner/Documents/Projects/test/test-latency/include/loguru
  include: /home/werner/Documents/Projects/test/test-latency/include/readerwriterqueue
  include: /home/werner/Documents/Projects/test/test-latency/include
  include: /home/werner/Documents/Projects/test/test-latency/builddir/src/test_utils
  include: /home/werner/Documents/Projects/test/test-latency/src/test_utils
  include: /usr/include/c++/10
  include: /usr/include/x86_64-linux-gnu/c++/10
  include: /usr/include/c++/10/backward
  include: /usr/lib/gcc/x86_64-linux-gnu/10/include
  include: /usr/local/include
  include: /usr/include/x86_64-linux-gnu
  include: /usr/include
  define: __STDC__=1
  define: __cplusplus=201703L
  define: __STDC_UTF_16__=1
  define: __STDC_UTF_32__=1
  define: __STDC_HOSTED__=1
  define: __GNUC__=10
  define: __GNUC_MINOR__=2
  define: __GNUC_PATCHLEVEL__=0
  define: __VERSION__="10.2.0"
  define: __ATOMIC_RELAXED=0
  define: __ATOMIC_SEQ_CST=5
  define: __ATOMIC_ACQUIRE=2
  define: __ATOMIC_RELEASE=3
  define: __ATOMIC_ACQ_REL=4
  define: __ATOMIC_CONSUME=1
  define: __pic__=2
  define: __PIC__=2
  define: __pie__=2
  define: __PIE__=2
  define: __FINITE_MATH_ONLY__=0
  define: _LP64=1
  define: __LP64__=1
  define: __SIZEOF_INT__=4
  define: __SIZEOF_LONG__=8
  define: __SIZEOF_LONG_LONG__=8
  define: __SIZEOF_SHORT__=2
  define: __SIZEOF_FLOAT__=4
  define: __SIZEOF_DOUBLE__=8
  define: __SIZEOF_LONG_DOUBLE__=16
  define: __SIZEOF_SIZE_T__=8
  define: __CHAR_BIT__=8
  define: __BIGGEST_ALIGNMENT__=16
  define: __ORDER_LITTLE_EtestAN__=1234
  define: __ORDER_BIG_EtestAN__=4321
  define: __ORDER_PDP_EtestAN__=3412
  define: __BYTE_ORDER__=__ORDER_LITTLE_EtestAN__
  define: __FLOAT_WORD_ORDER__=__ORDER_LITTLE_EtestAN__
  define: __SIZEOF_POINTER__=8
  define: __GNUG__=10
  define: __SIZE_TYPE__=long unsigned int
  define: __PTRDIFF_TYPE__=long int
  define: __WCHAR_TYPE__=int
  define: __WINT_TYPE__=unsigned int
  define: __INTMAX_TYPE__=long int
  define: __UINTMAX_TYPE__=long unsigned int
  define: __CHAR16_TYPE__=short unsigned int
  define: __CHAR32_TYPE__=unsigned int
  define: __SIG_ATOMIC_TYPE__=int
  define: __INT8_TYPE__=signed char
  define: __INT16_TYPE__=short int
  define: __INT32_TYPE__=int
  define: __INT64_TYPE__=long int
  define: __UINT8_TYPE__=unsigned char
  define: __UINT16_TYPE__=short unsigned int
  define: __UINT32_TYPE__=unsigned int
  define: __UINT64_TYPE__=long unsigned int
  define: __INT_LEAST8_TYPE__=signed char
  define: __INT_LEAST16_TYPE__=short int
  define: __INT_LEAST32_TYPE__=int
  define: __INT_LEAST64_TYPE__=long int
  define: __UINT_LEAST8_TYPE__=unsigned char
  define: __UINT_LEAST16_TYPE__=short unsigned int
  define: __UINT_LEAST32_TYPE__=unsigned int
  define: __UINT_LEAST64_TYPE__=long unsigned int
  define: __INT_FAST8_TYPE__=signed char
  define: __INT_FAST16_TYPE__=long int
  define: __INT_FAST32_TYPE__=long int
  define: __INT_FAST64_TYPE__=long int
  define: __UINT_FAST8_TYPE__=unsigned char
  define: __UINT_FAST16_TYPE__=long unsigned int
  define: __UINT_FAST32_TYPE__=long unsigned int
  define: __UINT_FAST64_TYPE__=long unsigned int
  define: __INTPTR_TYPE__=long int
  define: __UINTPTR_TYPE__=long unsigned int
  define: __GXX_WEAK__=1
  define: __DEPRECATED=1
  define: __GXX_RTTI=1
  define: __GXX_EXPERIMENTAL_CXX0X__=1
  define: __STDCPP_DEFAULT_NEW_ALIGNMENT__=16
  define: __EXCEPTIONS=1
  define: __GXX_ABI_VERSION=1014
  define: __SCHAR_MAX__=0x7f
  define: __SHRT_MAX__=0x7fff
  define: __INT_MAX__=0x7fffffff
  define: __LONG_MAX__=0x7fffffffffffffffL
  define: __LONG_LONG_MAX__=0x7fffffffffffffffLL
  define: __WCHAR_MAX__=0x7fffffff
  define: __WCHAR_MIN__=(-__WCHAR_MAX__ - 1)
  define: __WINT_MAX__=0xffffffffU
  define: __WINT_MIN__=0U
  define: __PTRDIFF_MAX__=0x7fffffffffffffffL
  define: __SIZE_MAX__=0xffffffffffffffffUL
  define: __SCHAR_WIDTH__=8
  define: __SHRT_WIDTH__=16
  define: __INT_WIDTH__=32
  define: __LONG_WIDTH__=64
  define: __LONG_LONG_WIDTH__=64
  define: __WCHAR_WIDTH__=32
  define: __WINT_WIDTH__=32
  define: __PTRDIFF_WIDTH__=64
  define: __SIZE_WIDTH__=64
  define: __INTMAX_MAX__=0x7fffffffffffffffL
  define: __INTMAX_C(c)=c ## L
  define: __UINTMAX_MAX__=0xffffffffffffffffUL
  define: __UINTMAX_C(c)=c ## UL
  define: __INTMAX_WIDTH__=64
  define: __SIG_ATOMIC_MAX__=0x7fffffff
  define: __SIG_ATOMIC_MIN__=(-__SIG_ATOMIC_MAX__ - 1)
  define: __SIG_ATOMIC_WIDTH__=32
  define: __INT8_MAX__=0x7f
  define: __INT16_MAX__=0x7fff
  define: __INT32_MAX__=0x7fffffff
  define: __INT64_MAX__=0x7fffffffffffffffL
  define: __UINT8_MAX__=0xff
  define: __UINT16_MAX__=0xffff
  define: __UINT32_MAX__=0xffffffffU
  define: __UINT64_MAX__=0xffffffffffffffffUL
  define: __INT_LEAST8_MAX__=0x7f
  define: __INT8_C(c)=c
  define: __INT_LEAST8_WIDTH__=8
  define: __INT_LEAST16_MAX__=0x7fff
  define: __INT16_C(c)=c
  define: __INT_LEAST16_WIDTH__=16
  define: __INT_LEAST32_MAX__=0x7fffffff
  define: __INT32_C(c)=c
  define: __INT_LEAST32_WIDTH__=32
  define: __INT_LEAST64_MAX__=0x7fffffffffffffffL
  define: __INT64_C(c)=c ## L
  define: __INT_LEAST64_WIDTH__=64
  define: __UINT_LEAST8_MAX__=0xff
  define: __UINT8_C(c)=c
  define: __UINT_LEAST16_MAX__=0xffff
  define: __UINT16_C(c)=c
  define: __UINT_LEAST32_MAX__=0xffffffffU
  define: __UINT32_C(c)=c ## U
  define: __UINT_LEAST64_MAX__=0xffffffffffffffffUL
  define: __UINT64_C(c)=c ## UL
  define: __INT_FAST8_MAX__=0x7f
  define: __INT_FAST8_WIDTH__=8
  define: __INT_FAST16_MAX__=0x7fffffffffffffffL
  define: __INT_FAST16_WIDTH__=64
  define: __INT_FAST32_MAX__=0x7fffffffffffffffL
  define: __INT_FAST32_WIDTH__=64
  define: __INT_FAST64_MAX__=0x7fffffffffffffffL
  define: __INT_FAST64_WIDTH__=64
  define: __UINT_FAST8_MAX__=0xff
  define: __UINT_FAST16_MAX__=0xffffffffffffffffUL
  define: __UINT_FAST32_MAX__=0xffffffffffffffffUL
  define: __UINT_FAST64_MAX__=0xffffffffffffffffUL
  define: __INTPTR_MAX__=0x7fffffffffffffffL
  define: __INTPTR_WIDTH__=64
  define: __UINTPTR_MAX__=0xffffffffffffffffUL
  define: __GCC_IEC_559=2
  define: __GCC_IEC_559_COMPLEX=2
  define: __FLT_EVAL_METHOD__=0
  define: __FLT_EVAL_METHOD_TS_18661_3__=0
  define: __DEC_EVAL_METHOD__=2
  define: __FLT_RADIX__=2
  define: __FLT_MANT_DIG__=24
  define: __FLT_DIG__=6
  define: __FLT_MIN_EXP__=(-125)
  define: __FLT_MIN_10_EXP__=(-37)
  define: __FLT_MAX_EXP__=128
  define: __FLT_MAX_10_EXP__=38
  define: __FLT_DECIMAL_DIG__=9
  define: __FLT_MAX__=3.40282346638528859811704183484516925e+38F
  define: __FLT_NORM_MAX__=3.40282346638528859811704183484516925e+38F
  define: __FLT_MIN__=1.17549435082228750796873653722224568e-38F
  define: __FLT_EPSILON__=1.19209289550781250000000000000000000e-7F
  define: __FLT_DENORM_MIN__=1.40129846432481707092372958328991613e-45F
  define: __FLT_HAS_DENORM__=1
  define: __FLT_HAS_INFINITY__=1
  define: __FLT_HAS_QUIET_NAN__=1
  define: __DBL_MANT_DIG__=53
  define: __DBL_DIG__=15
  define: __DBL_MIN_EXP__=(-1021)
  define: __DBL_MIN_10_EXP__=(-307)
  define: __DBL_MAX_EXP__=1024
  define: __DBL_MAX_10_EXP__=308
  define: __DBL_DECIMAL_DIG__=17
  define: __DBL_MAX__=double(1.79769313486231570814527423731704357e+308L)
  define: __DBL_NORM_MAX__=double(1.79769313486231570814527423731704357e+308L)
  define: __DBL_MIN__=double(2.22507385850720138309023271733240406e-308L)
  define: __DBL_EPSILON__=double(2.22044604925031308084726333618164062e-16L)
  define: __DBL_DENORM_MIN__=double(4.94065645841246544176568792868221372e-324L)
  define: __DBL_HAS_DENORM__=1
  define: __DBL_HAS_INFINITY__=1
  define: __DBL_HAS_QUIET_NAN__=1
  define: __LDBL_MANT_DIG__=64
  define: __LDBL_DIG__=18
  define: __LDBL_MIN_EXP__=(-16381)
  define: __LDBL_MIN_10_EXP__=(-4931)
  define: __LDBL_MAX_EXP__=16384
  define: __LDBL_MAX_10_EXP__=4932
  define: __DECIMAL_DIG__=21
  define: __LDBL_DECIMAL_DIG__=21
  define: __LDBL_MAX__=1.18973149535723176502126385303097021e+4932L
  define: __LDBL_NORM_MAX__=1.18973149535723176502126385303097021e+4932L
  define: __LDBL_MIN__=3.36210314311209350626267781732175260e-4932L
  define: __LDBL_EPSILON__=1.08420217248550443400745280086994171e-19L
  define: __LDBL_DENORM_MIN__=3.64519953188247460252840593361941982e-4951L
  define: __LDBL_HAS_DENORM__=1
  define: __LDBL_HAS_INFINITY__=1
  define: __LDBL_HAS_QUIET_NAN__=1
  define: __FLT32_MANT_DIG__=24
  define: __FLT32_DIG__=6
  define: __FLT32_MIN_EXP__=(-125)
  define: __FLT32_MIN_10_EXP__=(-37)
  define: __FLT32_MAX_EXP__=128
  define: __FLT32_MAX_10_EXP__=38
  define: __FLT32_DECIMAL_DIG__=9
  define: __FLT32_MAX__=3.40282346638528859811704183484516925e+38F32
  define: __FLT32_NORM_MAX__=3.40282346638528859811704183484516925e+38F32
  define: __FLT32_MIN__=1.17549435082228750796873653722224568e-38F32
  define: __FLT32_EPSILON__=1.19209289550781250000000000000000000e-7F32
  define: __FLT32_DENORM_MIN__=1.40129846432481707092372958328991613e-45F32
  define: __FLT32_HAS_DENORM__=1
  define: __FLT32_HAS_INFINITY__=1
  define: __FLT32_HAS_QUIET_NAN__=1
  define: __FLT64_MANT_DIG__=53
  define: __FLT64_DIG__=15
  define: __FLT64_MIN_EXP__=(-1021)
  define: __FLT64_MIN_10_EXP__=(-307)
  define: __FLT64_MAX_EXP__=1024
  define: __FLT64_MAX_10_EXP__=308
  define: __FLT64_DECIMAL_DIG__=17
  define: __FLT64_MAX__=1.79769313486231570814527423731704357e+308F64
  define: __FLT64_NORM_MAX__=1.79769313486231570814527423731704357e+308F64
  define: __FLT64_MIN__=2.22507385850720138309023271733240406e-308F64
  define: __FLT64_EPSILON__=2.22044604925031308084726333618164062e-16F64
  define: __FLT64_DENORM_MIN__=4.94065645841246544176568792868221372e-324F64
  define: __FLT64_HAS_DENORM__=1
  define: __FLT64_HAS_INFINITY__=1
  define: __FLT64_HAS_QUIET_NAN__=1
  define: __FLT128_MANT_DIG__=113
  define: __FLT128_DIG__=33
  define: __FLT128_MIN_EXP__=(-16381)
  define: __FLT128_MIN_10_EXP__=(-4931)
  define: __FLT128_MAX_EXP__=16384
  define: __FLT128_MAX_10_EXP__=4932
  define: __FLT128_DECIMAL_DIG__=36
  define: __FLT128_MAX__=1.18973149535723176508575932662800702e+4932F128
  define: __FLT128_NORM_MAX__=1.18973149535723176508575932662800702e+4932F128
  define: __FLT128_MIN__=3.36210314311209350626267781732175260e-4932F128
  define: __FLT128_EPSILON__=1.92592994438723585305597794258492732e-34F128
  define: __FLT128_DENORM_MIN__=6.47517511943802511092443895822764655e-4966F128
  define: __FLT128_HAS_DENORM__=1
  define: __FLT128_HAS_INFINITY__=1
  define: __FLT128_HAS_QUIET_NAN__=1
  define: __FLT32X_MANT_DIG__=53
  define: __FLT32X_DIG__=15
  define: __FLT32X_MIN_EXP__=(-1021)
  define: __FLT32X_MIN_10_EXP__=(-307)
  define: __FLT32X_MAX_EXP__=1024
  define: __FLT32X_MAX_10_EXP__=308
  define: __FLT32X_DECIMAL_DIG__=17
  define: __FLT32X_MAX__=1.79769313486231570814527423731704357e+308F32x
  define: __FLT32X_NORM_MAX__=1.79769313486231570814527423731704357e+308F32x
  define: __FLT32X_MIN__=2.22507385850720138309023271733240406e-308F32x
  define: __FLT32X_EPSILON__=2.22044604925031308084726333618164062e-16F32x
  define: __FLT32X_DENORM_MIN__=4.94065645841246544176568792868221372e-324F32x
  define: __FLT32X_HAS_DENORM__=1
  define: __FLT32X_HAS_INFINITY__=1
  define: __FLT32X_HAS_QUIET_NAN__=1
  define: __FLT64X_MANT_DIG__=64
  define: __FLT64X_DIG__=18
  define: __FLT64X_MIN_EXP__=(-16381)
  define: __FLT64X_MIN_10_EXP__=(-4931)
  define: __FLT64X_MAX_EXP__=16384
  define: __FLT64X_MAX_10_EXP__=4932
  define: __FLT64X_DECIMAL_DIG__=21
  define: __FLT64X_MAX__=1.18973149535723176502126385303097021e+4932F64x
  define: __FLT64X_NORM_MAX__=1.18973149535723176502126385303097021e+4932F64x
  define: __FLT64X_MIN__=3.36210314311209350626267781732175260e-4932F64x
  define: __FLT64X_EPSILON__=1.08420217248550443400745280086994171e-19F64x
  define: __FLT64X_DENORM_MIN__=3.64519953188247460252840593361941982e-4951F64x
  define: __FLT64X_HAS_DENORM__=1
  define: __FLT64X_HAS_INFINITY__=1
  define: __FLT64X_HAS_QUIET_NAN__=1
  define: __DEC32_MANT_DIG__=7
  define: __DEC32_MIN_EXP__=(-94)
  define: __DEC32_MAX_EXP__=97
  define: __DEC32_MIN__=1E-95DF
  define: __DEC32_MAX__=9.999999E96DF
  define: __DEC32_EPSILON__=1E-6DF
  define: __DEC32_SUBNORMAL_MIN__=0.000001E-95DF
  define: __DEC64_MANT_DIG__=16
  define: __DEC64_MIN_EXP__=(-382)
  define: __DEC64_MAX_EXP__=385
  define: __DEC64_MIN__=1E-383DD
  define: __DEC64_MAX__=9.999999999999999E384DD
  define: __DEC64_EPSILON__=1E-15DD
  define: __DEC64_SUBNORMAL_MIN__=0.000000000000001E-383DD
  define: __DEC128_MANT_DIG__=34
  define: __DEC128_MIN_EXP__=(-6142)
  define: __DEC128_MAX_EXP__=6145
  define: __DEC128_MIN__=1E-6143DL
  define: __DEC128_MAX__=9.999999999999999999999999999999999E6144DL
  define: __DEC128_EPSILON__=1E-33DL
  define: __DEC128_SUBNORMAL_MIN__=0.000000000000000000000000000000001E-6143DL
  define: __REGISTER_PREFIX__=
  define: __USER_LABEL_PREFIX__=
  define: __GNUC_STDC_INLINE__=1
  define: __NO_INLINE__=1
  define: __STRICT_ANSI__=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_8=1
  define: __GCC_ATOMIC_BOOL_LOCK_FREE=2
  define: __GCC_ATOMIC_CHAR_LOCK_FREE=2
  define: __GCC_ATOMIC_CHAR16_T_LOCK_FREE=2
  define: __GCC_ATOMIC_CHAR32_T_LOCK_FREE=2
  define: __GCC_ATOMIC_WCHAR_T_LOCK_FREE=2
  define: __GCC_ATOMIC_SHORT_LOCK_FREE=2
  define: __GCC_ATOMIC_INT_LOCK_FREE=2
  define: __GCC_ATOMIC_LONG_LOCK_FREE=2
  define: __GCC_ATOMIC_LLONG_LOCK_FREE=2
  define: __GCC_ATOMIC_TEST_AND_SET_TRUEVAL=1
  define: __GCC_ATOMIC_POINTER_LOCK_FREE=2
  define: __HAVE_SPECULATION_SAFE_VALUE=1
  define: __GCC_HAVE_DWARF2_CFI_ASM=1
  define: __PRAGMA_REDEFINE_EXTNAME=1
  define: __SSP_STRONG__=3
  define: __SIZEOF_INT128__=16
  define: __SIZEOF_WCHAR_T__=4
  define: __SIZEOF_WINT_T__=4
  define: __SIZEOF_PTRDIFF_T__=8
  define: __amd64=1
  define: __amd64__=1
  define: __x86_64=1
  define: __x86_64__=1
  define: __SIZEOF_FLOAT80__=16
  define: __SIZEOF_FLOAT128__=16
  define: __ATOMIC_HLE_ACQUIRE=65536
  define: __ATOMIC_HLE_RELEASE=131072
  define: __GCC_ASM_FLAG_OUTPUTS__=1
  define: __k8=1
  define: __k8__=1
  define: __code_model_small__=1
  define: __MMX__=1
  define: __SSE__=1
  define: __SSE2__=1
  define: __FXSR__=1
  define: __SSE_MATH__=1
  define: __SSE2_MATH__=1
  define: __MMX_WITH_SSE__=1
  define: __SEG_FS=1
  define: __SEG_GS=1
  define: __CET__=3
  define: __gnu_linux__=1
  define: __linux=1
  define: __linux__=1
  define: __unix=1
  define: __unix__=1
  define: __ELF__=1
  define: __DECIMAL_BID_FORMAT__=1
  define: _GNU_SOURCE=1
  define: _STDC_PREDEF_H=1
  define: __STDC_IEC_559__=1
  define: __STDC_IEC_559_COMPLEX__=1
  define: __STDC_ISO_10646__=201706L
  define: _FILE_OFFSET_BITS=64
  other: --g++
  other: --gnu_version=100200
  stdver: c++17
  intelliSenseMode: linux-gcc-x64
Checking for syntax errors: file:///home/werner/Documents/Projects/test/test-latency/src/test_latency_source.cpp
Queueing IntelliSense update for files in translation unit of: /home/werner/Documents/Projects/test/test-latency/src/test_latency_source.cpp
cpptools/getSemanticTokens: file:///home/werner/Documents/Projects/test/test-latency/src/test_latency_source.cpp (id: 4)
idle loop: reparsing the active document
cpptools/getCodeActions: file:///home/werner/Documents/Projects/test/test-latency/src/test_latency_source.cpp (id: 5)
cpptools/getFoldingRanges: file:///home/werner/Documents/Projects/test/test-latency/src/test_latency_source.cpp (id: 6)
Checking for syntax errors: file:///home/werner/Documents/Projects/test/test-latency/src/test_latency_source.cpp
Queueing IntelliSense update for files in translation unit of: /home/werner/Documents/Projects/test/test-latency/src/test_latency_source.cpp
cpptools/finishUpdateSquiggles
Error squiggle count: 13
terminating child process: 3891447
Update IntelliSense time (sec): 2.53
cpptools/activeDocumentChange: file:///home/werner/Documents/Projects/test/test-latency/src/test_latency_source.cpp
cpptools/textEditorSelectionChange
cpptools/getFoldingRanges: file:///home/werner/Documents/Projects/test/test-latency/src/test_latency_source.cpp (id: 7)
cpptools/getCodeActions: file:///home/werner/Documents/Projects/test/test-latency/src/test_latency_source.cpp (id: 8)
idle loop: reparsing the active document
Checking for syntax errors: file:///home/werner/Documents/Projects/test/test-latency/src/test_latency_source.cpp
Queueing IntelliSense update for files in translation unit of: /home/werner/Documents/Projects/test/test-latency/src/test_latency_source.cpp
cpptools/finishUpdateSquiggles
Error squiggle count: 13
Update IntelliSense time (sec): 0.283
cpptools/getSemanticTokens: file:///home/werner/Documents/Projects/test/test-latency/src/test_latency_source.cpp (id: 9)
cpptools/getFoldingRanges: file:///home/werner/Documents/Projects/test/test-latency/src/test_latency_source.cpp (id: 10)
cpptools/getCodeActions: file:///home/werner/Documents/Projects/test/test-latency/src/test_latency_source.cpp (id: 11)
```
</details>

**Comment by sean-mcmanus** [comment]
Your issue only occurs with macros in the header, right? If so, we may have an internal repro of this at https://github.com/microsoft/vscode-cpptools/issues/7270 . @Colengms Does that seem like the same issue to you?

**Comment by slhck** [comment]
Yes, it affects those macros only.

**Comment by sean-mcmanus** [comment]
I've filed an internal bug against our shared VS parser (with our internal repro). Hopefully they'll be able to fix it soon.

**Comment by slhck** [comment]
Thanks for the update!

**Comment by willco007** [comment]
I'm also seeing this issue on linux. All #defines in a .hpp header file and then included into another file will be resolved but then show the undefined error as @slhck reported.

**Comment by sean-mcmanus** [comment]
We believe this is fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0-insiders2

**Comment by slhck** [comment]
Yes, this is fixed now, thanks!

**Comment by sean-mcmanus** [comment]
Then it sounds like it's a different issue you're hitting. I think we may need some sort of isolated repro. You could try setting C_Cpp.intelliSenseCacheSize to 0 in case it's a bug with that caching.

**Comment by sean-mcmanus** [comment]
Well, one other thing to check is to go the definition of the macro that isn't defined and see if there are any IntelliSense errors reported or if the define is in an inactive region.

**Comment by slhck** [comment]
Thanks for the suggestions! There are no errors in the macro itself.

The errors disappeared when I turned off the cache by setting `C_Cpp.intelliSenseCacheSize` to 0 and reloaded the window, then waited for a bit.

I first didn't see it in my user settings and had to check in the settings tab for the remote context.

I turned the cache back on and the errors came back.

**Comment by marcoabensur** [comment]
Here I am having the same problem, and it was not fixed in 1.4.0. In version prior to 1.3.0 it was working.

- OS and Version: Ubuntu 20.04
- VS Code Version: Version: 1.56.2
- C/C++ Extension Version: v1.4.0-insiders2; 1.3.1
- Other extensions you installed (and if the issue persists after disabling them): N/A
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
```
src
├── ASF
│   ├── sam0
│         ├── port
│             └── port.h
├── user
│    └── user.c
└── board_config.h
```


In user.c file I have:

```
#include "board_config.h"
....
PLUV_SENSOR_POWER_ON
```

In board_config.h:
```
#include "port.h:"
...
#define PORT_EN_PLUV                               PORTA
#define PLUV_SENSOR_POWER_ON           PORT_EN_PLUV.OUTSET.reg =  (1UL << (IO_EN_PLUV % 32));
```

And in port.h:
```
#if (PORT_GROUPS > 0) || defined(__DOXYGEN__)
#  define PORTA             PORT->Group[0]
#endif
```

Lastly there is a bunch of definitions for PORT_GROUPS depending on which of the following header files was included in a file called "samd21.h" that port.h depend on:

samd21.h:
![image](https://user-images.githubusercontent.com/12650571/119038800-ed6e0280-b989-11eb-947c-b9ac6656b3f2.png)

And the right header to include is "samd21g18a.h" as "__SAMD21G18A__" was defined in c_cpp_properties.json

c_cpp_properties.json:
```
{
    "configurations": [
        {
            "name": "FieldPro_SAMD21",
            "includePath": [
                "${workspaceFolder}/**"
            ],

            "defines": [
                "__SAMD21G18A__"
            ],

            "compilerPath": "/home/fieldpro/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-gcc",
            "cStandard": "gnu99",
            "cppStandard": "c++14",
            "intelliSenseMode": "linux-gcc-arm"
        }
    ],
    "version": 4
}

```

**The problem**:

I get the message : "PORTA" is undefined, despite the fact that in samd21.h it knows which file to include correctly. And with ctrl+click I can go to the right definition.

With this same program and cpp_configuration it was working in previous versions. 

Also, even though i also tried to set `C_Cpp.intelliSenseCacheSize` to 0 it did not work.

**Comment by sean-mcmanus** [comment]
Okay, I'll see if I can repro it...

**Comment by willco007** [comment]
Disabling the cache also fixes it for me. The first time the parser runs, the defines are found correctly, but as soon as I edit the file they are lost which does indicate a cache issue.

**Comment by sean-mcmanus** [comment]
I'm still not able to repro this. Is anyone able to provide a sample repro project?

**Comment by slhck** [comment]
I'll try to set up a self contained example next week once I'm back at the Linux machine.

**Comment by marcoabensur** [comment]
I've made a self contained example for the issue I had observed.

While I was making the simplifications for the example, I found that probably my issue arises from the fact that my project had 2 files named "port.h". Before making this example I didn't see this error.

The project can compile without errors, and ctrl + click can still find the right file, even if there is 2 with the same name.

Maybe user "slhck" problem is different. Anyway, here is the link for the repo where I put the example : https://github.com/marcoabensur/identifier-undefined-issue

And here is an image showing the problem:
![image](https://user-images.githubusercontent.com/12650571/119278198-13014300-bbfa-11eb-92bd-cc14af94473c.png)

**Comment by sean-mcmanus** [comment]
@marcoabensur Your issue is "by design" and fixed by setting a non-recursive include path. The "**" (recursive include) path is choosing a different port.h path due to the name conflict so you need to specify a non-recursive path to take precedence. Another alternative to try would be to use the Makefile Tools extension and set `"configurationProvider": "ms-vscode.makefile-tools"` in c_cpp_properties.json.

![image](https://user-images.githubusercontent.com/19859882/119384430-8eeea000-bc79-11eb-9ffc-9259a858509d.png)

**Comment by marcoabensur** [comment]
Thank you!

**Comment by slhck** [comment]
I think I will not be able to reproduce this. Most probably it is caused by the logging library being included twice, once in a library and once in the main executable, which is not a good design anyway. I'm closing this for now and will come back if I can reliably reproduce this.
