### ISSUE TITLE
Latest version can no longer link the header files correctly!

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [microsoft/vscode-cpptools#741]
Althought when I press `Ctrl` and click the `#include "xxx.h"`, It can find and jump to the header file correctly, the lint export an error said `cannot open source file "xxx.h"`.

![image](https://cloud.githubusercontent.com/assets/12682063/26274122/89cb0d9e-3d74-11e7-8f13-0ec8ec5978b4.png)

This problem never appeared before `Version 0.11.1` update.

My project file structure was customize, perhaps caused? It looks like:
``` shell
project\src\
    - head\
        -- header files. (*.h)
        .......
    - main\
        -- main source code. (*.c)
```
U could get more informations details about the project, see [GitHub](https://github.com/zhengxiaoyao0716/PixelPet3D/tree/core)

**Comment by v3rDr3t** [comment]
I can confirm this. Having the exact same problems on Ubuntu 17.04x64 since the latest update.

**Comment by Ashod** [comment]
Same issue on Ubuntu.

**Comment by sangwon0001** [comment]
same issue on ubuntu with this settings
![image](https://cloud.githubusercontent.com/assets/13912540/26276137/44c135b0-3dac-11e7-91a4-d7336138d90f.png)

**Comment by bobbrow** [comment]
Are you all referring to the same GitHub project as @zhengxiaoyao0716?  To get the linter to work correctly, you need to add your include paths to the `"includePath"` array.  For the project @zhengxiaoyao0716 is referencing, it seems you would need to add `${workspaceRoot}/src/head` based on what I see in the repo.  The new linter requires that you add an entry in the `"includePath"` for each path that you would normally send to your compiler via `-I`

**Comment by boltzmanncte** [comment]
Hi @bobbrow I have the same problem on Ubuntu 16.04 and my c_cpp_properties.json just like @sangwon0001 's, looks like this:

![vsc_headererror](https://cloud.githubusercontent.com/assets/28837011/26282272/3a824ecc-3e06-11e7-8e7e-61870e05e0a1.png)

I am referring to my own project and the problem appeared after upgrading to version 0.11.1.

**Comment by zhengxiaoyao0716** [comment]
@bobbrow are right, After I insert `"${workspaceRoot}/src/head"` into `c_cpp_properties.json` file, it works, thanks.
![image](https://cloud.githubusercontent.com/assets/12682063/26282529/c2bde00a-3e45-11e7-8048-57294a66b625.png)

However, I don't like this way, it brings redundant files (Not only `c_cpp_properties` but a `settings.json` file) and doesn't flexible.

What's more, there are still some problem:
1. It can not lint the struct variable correctly, although the `Ctrl + Click ` can see the fileds prototype, the lint give the error `xxx is not defined`.
![image](https://cloud.githubusercontent.com/assets/12682063/26282807/1cf71974-3e4b-11e7-8394-55f3cf61cbdb.png)
![image](https://cloud.githubusercontent.com/assets/12682063/26282787/c94aa7c8-3e4a-11e7-87b9-1c81c7fa9b30.png)


2. I have a `server` module defined in `server.h` and implement with `server.c`, here those code:
``` C
/* server.h */
// ...
typedef void (*PP3DHandler)(IN char *recvBuf, OUT char *sendBuf);
// ...

/* server.c */
// ...
#include "server/server.h"
//...
#include "map.cpp.h"
// #include "map.c.h"
// ...
```
Then in map.cpp.h, it still give an error `identifier "PP3DHandler" is undefined` when I use. A strange problem is, in another implement file named `map.c.h`, it works well:
![image](https://cloud.githubusercontent.com/assets/12682063/26282689/c11b177e-3e48-11e7-83e1-b2128655c2e3.png)

**Comment by ThatJCB** [comment]
See also the workround in:
[https://github.com/Microsoft/vscode-cpptools/issues/743](https://github.com/Microsoft/vscode-cpptools/issues/743)

Someone with admin rights might want to merge some threads together.

**Comment by bobbrow** [comment]
@zhengxiaoyao0716 what compiler do you use to compile this C code?  I'm not familiar with the struct initialization syntax you've shown in your screenshots.

Are there any red underlines in your server.h file when you open it?  Is PP3DHandler defined within an inactive preprocessor block? (hover over the declaration to see)

**Comment by UR3IQO** [comment]
>  I'm not familiar with the struct initialization syntax you've shown in your screenshots.

It is an old GCC's syntax. Now obsolete (since GCC 2.5), but it is still supported by GCC https://gcc.gnu.org/onlinedocs/gcc/Designated-Inits.html#Designated-Inits

**Comment by zhengxiaoyao0716** [comment]
To @bobbrow : @sov1178 are right, it equals to this syntax: (don't mind the red underlines, I removed the ugly  `c_cpp_properties.js` and `settings.json` files so the linter report the `xxx is undefined` error again.)
![image](https://cloud.githubusercontent.com/assets/12682063/26388158/3a87d668-4085-11e7-96b0-cba28dac7f7a.png)
However, the old syntax is really legal and for me looks more elegance. I use this syntax to keep consistent with other language, such as Js、Python and Go. Most of modern language choised this Json object K-V pair syntax like `key: value`, instead of `.key = value`.

And here are my `server.h`, without red underlines and no special syntax except a function pointer type defined, used to simulate interface.
![image](https://cloud.githubusercontent.com/assets/12682063/26387909/dc034df8-4083-11e7-84b2-008bfa4998ff.png)

My project could correctly compiled cross my `Win10 PC` (both `Ubuntu bash` and `MinGW x64`), `Ubuntu 16.04` and `Raspbian`, here the [link](https://github.com/zhengxiaoyao0716/PixelPet3D/tree/core) and you can give a try.
- Win10 Ubuntu bash:
![image](https://cloud.githubusercontent.com/assets/12682063/26389070/9719cc24-408a-11e7-9868-3fa201c30dd0.png)
- MinGW x64:
![image](https://cloud.githubusercontent.com/assets/12682063/26389058/8823b5d6-408a-11e7-99b4-716c9a7f0210.png)
- Ubuntu 16.04:
![image](https://cloud.githubusercontent.com/assets/12682063/26389094/b98a4b62-408a-11e7-9c7d-bcc5791c7e14.png)
- Raspbian April 2017:
![image](https://cloud.githubusercontent.com/assets/12682063/26389210/50d0a43a-408b-11e7-9f4a-e9d5ee511d6f.png)

It works well and once looks pretty with lint, untill I update the plugin.
Excuse me that if I have to compromise with troubles config file, minority syntax and give up function interface, I prefer to abandon the plugin.

**Comment by zhengxiaoyao0716** [comment]
I found it helpfulf from #743 , @ThatJCB . With this setting:
![image](https://cloud.githubusercontent.com/assets/12682063/26401854/61cad452-40ba-11e7-9fed-e2fcaabe9394.png)
All problem above was resolved. However, when I use a struct variable, the lint works well, but if I use a struct function, it still report the same error like `xxx not found`, and cannot recognize the illegal use:
![image](https://cloud.githubusercontent.com/assets/12682063/26402418/d1f86e04-40bc-11e7-92e1-47097cc06945.png)
![image](https://cloud.githubusercontent.com/assets/12682063/26402321/6c55e82e-40bc-11e7-9a0b-5c44899bb076.png)

**Comment by bobbrow** [comment]
The Tag Parser does not do linting and does not have semantic awareness, so it cannot recognize any illegal use of methods/fields.

We are working on a change to disable the linting if any `#include` directives are not resolved so that you won't have to mess with the config files if you don't want to.

**Comment by zhengxiaoyao0716** [comment]
@bobbrow I've got the 0.11.2 update, thks .

**Comment by David-AJ** [comment]
@bobbrow My cpptools version is 0.12.0, and I'm having the same problem. The screenshot:        

![default](https://user-images.githubusercontent.com/17141828/28248188-c5f08cd8-6a72-11e7-98ed-1dfc8f57e769.png)         
It can find the header correctly when I press `Ctrl` and click the `#include "List.h"`. But I got this error when I was trying to compile `CPP_test.cpp`:         

`fatal error: List.h: No such file or directory`         

It seems like my GCC compiler can't find the header file `List.h`. My project file structure looks like:        
``` 
${workspaceRoot}\
    - Cpp File src\
        -- CPP_test.cpp
    - lib\
        -- List.h
```
And I've already added `${workspaceRoot}/lib` into `c_cpp_properties.json` file like:      
![default](https://user-images.githubusercontent.com/17141828/28248204-09ed6d5c-6a73-11e7-96dc-77820f882321.png)
@zhengxiaoyao0716 solved the problem when he inserted `"${workspaceRoot}/src/head"` into `c_cpp_properties.json` file. But it doesn't work in my computer.        
Please tell me how to fix it, thanks!

**Comment by zhengxiaoyao0716** [comment]
@David-AJ well, you get error just in compile? It seems you need a Makefile to tall g++ how to assemble and compile your code. Here are a [general makefile](https://github.com/zhengxiaoyao0716/general-makefile) create by me and you can use it after change the `Custome variables` to the correctly directory your porject need.

**Comment by David-AJ** [comment]
@zhengxiaoyao0716 Thank you for your help! But I'm just wondering if there's any possible to fix it by changing some setting files without using the makefile. Because I don't know how to use the makefile. Also if a makefile can to tell my g++ how to complie my code, it seems like I don't need the `c_cpp_properties.json`  and `tasks.json` files anymore.

**Comment by David-AJ** [comment]
Update
===
@bobbrow I have fixed my problem by adding my header path into `tasks.json` like:
![default](https://user-images.githubusercontent.com/17141828/28255094-b1c7e3c8-6ae5-11e7-85fd-babbdf963a87.png)
Thank you @zhengxiaoyao0716! Your words about telling my g++ how to compile really inspired me! I changed the command with `g++ -I` to add my header path.

**Comment by sean-mcmanus** [comment]
@David-AJ c_cpp_properties.json is for the IntelliSense compiler and tasks.json is for the actual compiler.

**Comment by zhengxiaoyao0716** [comment]
@David-AJ you are welcome, `Makefile` is outmoded and elusive, but I prefer to use it because it can give more infomation for compile, cross ide and platform, well task.json only works with vscode.

**Comment by LlorandoLau** [comment]
@bobbrow There is a same problem in my vscode. Here is my file.

tasks
![task](https://user-images.githubusercontent.com/28216165/31885764-40bf46f8-b824-11e7-81c9-7e8d0c218ca2.PNG)

c_cpp
![c_cpp](https://user-images.githubusercontent.com/28216165/31885963-fa3c1b60-b824-11e7-897e-a78f6fdaa03b.PNG)


and my folder is like this:
![folder](https://user-images.githubusercontent.com/28216165/31885839-7d310cde-b824-11e7-9199-39153560e33d.PNG)

What's wrong is it?

**Comment by sean-mcmanus** [comment]
@LlorandoLau Your databaseFilename seems strange and probably shouldn't be in "Program Files" (you might not have non-admin write access). You can change the C_Cpp.loggingLevel to "Warning" to see if there are any issues reported in the C/C++ output window pane.

**Comment by LlorandoLau** [comment]
@sean- mumanus I can read the header file in Mingw( throught databasefilename) . But I cannot read my own header file. For example, in picture 3, while linking to”header.h”, it’s warning “ no such a file”. I am sorry I don’t know how to adjust C_Cpp.loggingLevel ( it’s my first time to see this word ). Could you explain more clearly about it?

**Comment by bobbrow** [comment]
To adjust the logging level, press <kbd>Ctl</kbd>+<kbd>,</kbd> to open the settings file and search for "loggingLevel".  Hover over the setting and click the pencil icon to change the setting:

![image](https://user-images.githubusercontent.com/12818240/31897581-af7974a0-b7cb-11e7-87c2-f1b303a64437.png)

**Comment by bobbrow** [comment]
And like Sean said, that path looks suspect.  Try using `${workspaceRoot}/.vscode/browse.db` temporarily so we can rule out any path issues.

**Comment by LlorandoLau** [comment]
I change the routing and loggingLevel, but a new error `appear:

`Failed to launch external program g++ -g ${file} -o ${file}.exe.
spawn g++ ENOENT`

My json file is :
`
C_Cpp_properties
{
    "version": "0.2.0",
    "configurations": [{
        "name": "C++ Launch (GDB)", // 配置名称，将会在启动配置的下拉菜单中显示
        "type": "cppdbg", // 配置类型，这里只能为cppdbg
        "request": "launch", // 请求配置类型，可以为launch（启动）或attach（附加）
        "targetArchitecture": "x86", // 生成目标架构，一般为x86或x64，可以为x86, arm, arm64, mips, x64, amd64, x86_64
        "program": "${file}.exe", // 将要进行调试的程序的路径

        "miDebuggerPath": "C:\\program files\\MinGW\\bin\\gdb.exe", // miDebugger的路径，注意这里要与MinGw的路径对应

        "args": [], // 程序调试时传递给程序的命令行参数，一般设为空即可
        "stopAtEntry": false, // 设为true时程序将暂停在程序入口处，一般设置为false
        "cwd": "${fileDirname}", // 调试程序时的工作目录，一般为${workspaceRoot}即代码所在目录
        "externalConsole": true, // 调试时是否显示控制台窗口，一般设置为true显示控制台
        "preLaunchTask": "g++"　　 // 调试会话开始前执行的任务，一般为编译程序，c++为g++, c为gcc
    }]
}`

`launchu
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "/usr/include",
                "/usr/local/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include",
                    "/usr/local/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ]
        },
        {
            "name": "Linux",
            "includePath": [
                "/usr/include",
                "/usr/local/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include",
                    "/usr/local/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        },
        {
            "name": "Win32",
            "includePath": [
                "${workspaceRoot}"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE"
            ],
            "intelliSenseMode": "msvc-x64",
            "browse": {
                "path": [
                    "${workspaceRoot}",
                    "C:\\Program Files\\MinGW\\bin"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": "${workspaceRoot}/.vscode/browse.db"
            }
        }
    ],
    "version": 3
}`
task.json
`{
    "version": "0.1.0",
    "command": "g++",
    "args": ["-g","${file}","-o","${file}.exe"],    // 编译命令参数
    "problemMatcher": {
        "owner": "cpp",
        "fileLocation": ["relative", "${workspaceRoot}"],
        "pattern": {
            "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
            "file": 1,
            "line": 2,
            "column": 3,
            "severity": 4,
            "message": 5
        }
    }
}`

**Comment by LlorandoLau** [comment]
@bobbrow I change the route and logginglevel, but a new error appear:

![error](https://user-images.githubusercontent.com/28216165/31918644-59be040c-b890-11e7-8640-769177ed5b95.PNG)


and my json file is:

launch.json:

![launch](https://user-images.githubusercontent.com/28216165/31918727-d0decfee-b890-11e7-8cea-d58d16327d71.PNG)

task.json:
![task](https://user-images.githubusercontent.com/28216165/31918731-d6db044e-b890-11e7-9bb6-07efeeb05e34.PNG)

c_cpp_properties.json
![c_cpp](https://user-images.githubusercontent.com/28216165/31918735-dc59d8dc-b890-11e7-9e31-66650eadae97.PNG)

**Comment by sean-mcmanus** [comment]
@LlorandoLau That error appears to be a problem with your build task.json and not the cpptools extension. `${file}` seems to resolve to the currently opened file's full path. Maybe you want `${fileBasenameNoExtension}`.

**Comment by LlorandoLau** [comment]
@sean-mcmanus I change task.json. 
![task](https://user-images.githubusercontent.com/28216165/31919447-2cc85420-b895-11e7-814c-58bcb454e853.PNG)

But the error goes on:
![ex](https://user-images.githubusercontent.com/28216165/31919438-12f09c10-b895-11e7-931d-982d6b819993.PNG)

the other json files are no changed

**Comment by sean-mcmanus** [comment]
@LlorandoLau That is an error with your build task and not the cpptools extension.  I think you need to set the include path with `-I/path` (i.e. https://stackoverflow.com/questions/6141147/how-do-i-include-a-path-to-libraries-in-g ).

**Comment by David-AJ** [comment]
@LlorandoLau I think you should change the tasks.json. Like I shown before:
![default](https://user-images.githubusercontent.com/17141828/31920496-fc164bd2-b89b-11e7-824e-fa5d53fe20cd.JPG)
Use the "-I” command to tell your compiler how to find your headers.

**Comment by LlorandoLau** [comment]
@David-AJ @sean-mcmanus I try two way as those in pictures and stackoverflow, it could run on debugging. But when I push "run code", the error appears again:

![task](https://user-images.githubusercontent.com/28216165/31925086-bc8c0a84-b8b8-11e7-8df6-596df01ee7a0.PNG)

By the way, They can work on cmd:
![ex](https://user-images.githubusercontent.com/28216165/31925795-a11ea7f2-b8bd-11e7-888c-84e096399337.PNG)

**Comment by bobbrow** [comment]
Did you save the tasks.json file?  Or is VS Code not updating your task?  The output doesn't appear to match what you've written in the tasks.json file.

![image](https://user-images.githubusercontent.com/12818240/31952924-a32d97f0-b896-11e7-8101-a38498fe8545.png)

**Comment by LlorandoLau** [comment]
@bobbrow Yes, the tasks.json file was saved. And it could run while debugging. The error appeared when I choose “Run code” (ctrl+alt+n). How to correct it?

**Comment by LlorandoLau** [comment]
Is there any other place to make settings of “Run code”?

**Comment by sean-mcmanus** [comment]
@LlorandoLau I don't see a "Run code (ctrl+alt+n)" command. Is that coming from another extension you have installed?

**Comment by LlorandoLau** [comment]
@sean-mcmanus Maybe it is. I download many extensions as soon as I complete the installation. So I think the command is original.  Is there a way that I can check whick extension the command belongs to?

**Comment by sean-mcmanus** [comment]
@LlorandoLau If you click on the extension in the Extensions panel and click the Contributions tab you can see the list of commands an extension publishes.

**Comment by LlorandoLau** [comment]
@sean-mcmanus Alright, thanks

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity.
