### ISSUE TITLE
1.6.0-insiders2 update loop

### ISSUE THREAD

**Issue by BMBurstein** [microsoft/vscode-cpptools#8000]
Issue Type: <b>Bug</b>

The extension seems to be stuck in an update loop. I get this message:

The C/C++ Extension has been updated to version 1.5.1. Please reload the window for the changes to take effect.

And after I reload, I get this message:

The C/C++ Extension has been updated to version 1.6.0-insiders2. Please reload the window for the changes to take effect.

And after a reload I get the first one again etc...

Extension version: 1.5.1
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.3.0-28-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.45GB free)|
|Process Argv|--crash-reporter-id 6949b6e9-d952-4b8f-a136-284374926c80|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ubumews7748|
|OS|Linux x64 5.3.0-28-generic|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 4077)|
|Memory (System)|15.50GB (4.98GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30322571
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30353136

```

</details>

ase paste.

**Comment by cg31** [comment]
The same message but for version 1.6 "The C/C++ Extension has been updated to version 1.6.0-insiders2." is bugging me mad.

**Comment by janjensendk** [comment]
I'm also stuck between 1.5.1 and 1.6.0-insider2. I tried reinstalling VSCode including the extension, but no luck.

**Comment by eddie-kr** [comment]
> I'm also stuck between 1.5.1 and 1.6.0-insider2. I tried reinstalling VSCode including the extension, but no luck.

same here

**Comment by michelleangela** [comment]
Thank you for reporting this issue on updating the extension. 

We are able to reproduce this is as well. While we investigate and find a fix, please set the `C_Cpp.updateChannel` setting to "Default" as a workaround:

![image](https://user-images.githubusercontent.com/38734287/129936925-21db7d79-4767-4190-94ed-b947b8a9151d.png)

**Comment by shuvalov-mdb** [comment]
Same fort me

**Comment by Colengms** [comment]
This may be a VS Code bug.  It looks like it's installing our last released version over our insiders.  I'm not sure why it didn't happen with the first 1.6.0-insiders.  Maybe it has something to do with a version check failing due to the '2' at the end.  Setting the following will also prevent the loop: `"extensions.autoUpdate": false`

**Comment by Colengms** [comment]
Ok, this is a cpptools issue.  The scope of the `C_Cpp.updateChannel` has changed, such that it can be varied on a remote machine.  Prior to updating, it will use the same value as the client machine.  After updating, it will have a new-machine specific value on the host (which will be false, by default) causing cpptools to downgrade itself.

This issue should resolve itself when 1.6.0 is released.

**Comment by Colengms** [comment]
We're going to revert the `updateChannel` scope after all, and open an issue against VS Code requesting a scope that would inherit the local machine setting unless overridden on the remote machine.

**Comment by sean-mcmanus** [comment]
I'm still seeing a problem when using VS Code Insiders -- the setting of the default updateChannel to "Insiders" is failing to happen "sometimes", causing it to dowgrade to 1.5.1 and when it fails for 1.5.1 it doesn't upgrade to 1.6.0-insiders3 (until "randomly" it'll start working). Might be a VS Code Insiders bug?

**Comment by sean-mcmanus** [comment]
I filed bug https://github.com/microsoft/vscode/issues/131208 . The workaround is to explicitly set the updateChannel to Insiders.

**Comment by sean-mcmanus** [comment]
The issue that reproed with VS Code Insiders with the default updateChannel setting is fixed by https://github.com/microsoft/vscode-cpptools/pull/8032 .
