### ISSUE TITLE
cpptools process crashes on `interface_from_context_helper`

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#8312]
Hi, thanks for the tip. 

Here is the crash: https://pastebin.com/wkL3nGki It seems to be an exception on thread 4.

I am on Ubuntu 20, local machine.

_Originally posted by @bruno-kakele in https://github.com/microsoft/vscode-cpptools/issues/8080#issuecomment-947219394_

**Comment by michelleangela** [comment]
@bruno-kakele
Could you try C++ extension version 1.7.1 if you haven't yet and see if the crash still repros? Or is the callstack crash from 1.7.1?

**Comment by Colengms** [comment]
This issue is related to a use of `std::random_device` to generate a uuid. On some systems, it's not returning random numbers as expected.  One possibility of this is use of an AMD Ryzen 3000 series processor, in which there was a bug in the RDRAND instruction. If that's what's happening in your case, updating your motherboard's bios may address it.

**Comment by bruno-kakele** [comment]
Updating the bios fixed it, thank you! (I have a Ryzen 3600)

**Comment by sean-mcmanus** [comment]
It's also fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.0-insiders if anyone else is hitting this with the non-updated bios.

**Comment by dbogatov** [comment]
When is the stable 1.8 planned?

**Comment by sean-mcmanus** [comment]
@dbogatov Not till mid January, since our team has lots of vacations.

**Comment by dbogatov** [comment]
BTW, I installed the insiders version on remote iMac and it still fails.
What I noticed is that to trigger the failure I just need to recompile the binary.
Is the fix supposed to solve that too?

**Comment by sean-mcmanus** [comment]
What do you mean by "recompile the binary"? Are you hitting the interface_from_context_helper crash?

**Comment by dbogatov** [comment]
I mean that in my case the extension process doesn’t crash randomly, it crashes couple seconds after I run g++ command. Obviously it doesn’t crash if g++ fails (say compilation errors). Apparently it crashes if the binary file is updated. 

I’m not sure if it’s the “interface_from_context_helper”, I only see the “server will not be restarted” error. At which point I just “reload” vscode and extension works again.

**Comment by sean-mcmanus** [comment]
Your issue sounds unrelated. Can you file a new bug and get a call stack from the crash after attaching a debugger to cpptools? See https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv .

Normally, running g++ to build a new binary should have absolutely no effect on our cpptools process...maybe our file watcher is doing something it shouldn't be. Adding the path to the binary to `C_Cpp.files.exclude` may be a workaround for the crash, since that should cause the file watch to skip the changed file.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.0-insiders3 or 1.8.0 (via using VS Code's "Pre-Release Version" UI or https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools&ssr=false#version-history ).

**Comment by sean-mcmanus** [comment]
Oops, sorry, this was already fixed with 1.8.0-insiders.
